[package]
authors = ["sergey shmakov <tyfaproject@gmail.com>"]
edition = "2018"
name = "tufa_backend"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#egg-mode = "0.15.0"//twitter
futures = "0.3.5"
futures-async-stream = "0.2.2"
#google-youtube3 = "1.0.13+20200402" - не видит установленное openssl, под линуксом все норм
# quick-xml = "0.18.1"
reqwest = {version = "0.11.0", features = ["json","blocking"]}
roux = "0.4.0"
log = "0.4"
simplelog = "0.9"
serde = "1.0"
serde-xml-rs = "0.4.0"
serde_derive = "1.0"
serde_json = "1.0"
chrono = "0.4"
tokio = {version = "1.1.0", features = ["macros"]}
# tokio = {version = "0.2.21", features = ["macros"]}
ansi_term = "0.12"
# crossbeam = "0.8.0"
num_cpus = "1.0"
# threadpool = "1.0"
# RustyXML = "0.3.0"
# xml-rs = "0.8" 
# xmlparser = "0.13.2" 
#google-youtube3-cli = "1.0.13+20200402" коммандная строка - не то но как вариант можно стырить кое че
