[package]
authors = ["sergey shmakov <tyfaproject@gmail.com>"]
edition = "2018"
name = "tufa_backend"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
roux = "0.4.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
