[package]
authors = ["sergey shmakov <tyfaproject@gmail.com>"]
edition = "2018"
name = "tufa_backend"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3.5"
futures-async-stream = "0.2.2"
reqwest = {version = "0.11.0", features = ["json","blocking"]}
roux = "0.4.0"
serde = "1.0"
serde-xml-rs = "0.4.0"
serde_derive = "1.0"
serde_json = "1.0"
chrono = "0.4"
tokio = {version = "1.7.1", features = ["macros"]}
ansi_term = "0.12"
num_cpus = "1.0"
toml = "0.5"
html_parser = "0.6.2"
regex = "1.5"
# mongodb = "0.9.2"#some error while running tests with it
diesel = { version = "1.4.7", features = ["postgres"] }
dotenv = "0.15.0" #for diesel tutorial
config_lib = { path = "./libs/config_lib" }
providers_info_lib = { path = "./libs/providers_info_lib" }
mongo_demo = { path = "./libs/mongo_demo" }
#egg-mode = "0.15.0"//twitter
#google-youtube3 = "1.0.13+20200402" - do not saw openssl, under linux its all good
# quick-xml = "0.18.1"
# log = "0.4"
# simplelog = "0.9"
# tokio = {version = "0.2.0", features = ["macros"]}
# tokio-compat = "0.1.6"
# crossbeam = "0.8.0"
# async-std = "1.9.0"#remove later its only for example
# threadpool = "1.0"
# RustyXML = "0.3.0"
# xml-rs = "0.8" 
# xmlparser = "0.13.2" 
#google-youtube3-cli = "1.0.13+20200402" comand line interface as variant or just can use source code
# strum = { version = "0.20", features = ["derive"] }#for enum into string
#tutorial from https://blog.logrocket.com/configuration-management-in-rust-web-services/
# warp = "0.2"
#tutorial from https://blog.logrocket.com/configuration-management-in-rust-web-services/

[dev-dependencies]
tests_lib = { path = "./libs/tests_lib" }