version: '3.8'
services:
  postgres_service:
    container_name: postgres_container
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    volumes:
      - ./postgresql_volume:/data/db
    ports:
      - 5432:5432
  mongodb_service:
    container_name: mongodb_container
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_volume:/data/db
  # rust-backend:
  #   image: "rust:1.47"
  #   volumes:
  #     - ./tufa_backend:/tufa_backend
  #   environment: 
  #     - USER=sergey
volumes:
  postgresql_volume:
  mongodb_volume: