version: '3.8'
services:
  postgres_service:
    container_name: postgres_container
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    volumes:
      - ./postgresql_volume:/data/db
    ports:
      - 5432:5432
  mongodb_service:
    container_name: mongodb_container
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_volume:/data/db
  tufa_backend_service:
    container_name: tufa_backend-container
    image: tufa_backend-image
    restart: always
    ports:
      - 8000:8000
    env_file:
      - ./.env
    # environment: 
    #   PROJECT_RUN_MODE: "example" # Development, Production or Testing
    #   GITHUB_NAME: "example"
    #   GITHUB_TOKEN: "example"
    #   REDDIT_USER_AGENT: "example"
    #   REDDIT_CLIENT_ID: "example"
    #   REDDIT_CLIENT_SECRET: "example"
    #   REDDIT_USERNAME: "example"
    #   REDDIT_PASSWORD: "example"
    #   MONGO_OWN_LOGIN: "example"
    #   MONGO_OWN_PASSWORD: "example"
    #   MONGO_OWN_IP: "example"
    #   MONGO_OWN_PORT: "example"
    #   MONGO_CLOUD_LOGIN: "example"
    #   MONGO_CLOUD_PASSWORD: "example"
    #   MONGO_CLOUD_CLUSTER_NAME: "example"
    #   MONGO_CLOUD_CLUSTER_PARAMS: "example"
    #   POSTGRES_OWN_LOGIN: "example"
    #   POSTGRES_OWN_PASSWORD: "example"
    #   POSTGRES_OWN_IP: "example"
    #   POSTGRES_OWN_DB: "example"
volumes:
  postgresql_volume:
  mongodb_volume: