FROM rust:1.41-slim
WORKDIR /cache
RUN apt-get update
RUN USER=root cargo init --bin --vcs none
RUN ls
COPY . .
RUN ls
COPY Cargo.lock Cargo.toml /cache/ 
COPY /libs/config_lib/ .
COPY /libs/providers_info_lib/ .
RUN ls
RUN cargo build
RUN rm src/*.rs
RUN rm ./target/debug/deps/tufa_backend*
# RUN cargo build && rm src/*.rs && rm ./target/debug/deps/tufa_backend*
# sudo docker build -f dockerfile.cache -t kuqmua/tufa_tests .

# error[E0658]: subslice patterns are unstable
#    --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/object-0.23.0/src/read/mod.rs:162:41
#     |
# 162 |             [0x7f, b'E', b'L', b'F', 1, ..] => FileKind::Elf32,
#     |                                         ^^
#     |
#     = note: for more information, see https://github.com/rust-lang/rust/issues/62254

# error[E0658]: subslice patterns are unstable
#    --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/object-0.23.0/src/read/mod.rs:164:41
#     |
# 164 |             [0x7f, b'E', b'L', b'F', 2, ..] => FileKind::Elf64,
#     |                                         ^^
#     |
#     = note: for more information, see https://github.com/rust-lang/rust/issues/62254

# error[E0658]: subslice patterns are unstable
#    --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/object-0.23.0/src/read/mod.rs:166:38
#     |
# 166 |             [0xfe, 0xed, 0xfa, 0xce, ..]
#     |                                      ^^
#     |
#     = note: for more information, see https://github.com/rust-lang/rust/issues/62254

# error[E0658]: subslice patterns are unstable
#    --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/object-0.23.0/src/read/mod.rs:167:40
#     |
# 167 |             | [0xce, 0xfa, 0xed, 0xfe, ..] => FileKind::MachO32,
#     |                                        ^^
#     |
#     = note: for more information, see https://github.com/rust-lang/rust/issues/62254

# error[E0658]: subslice patterns are unstable
#    --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/object-0.23.0/src/read/mod.rs:169:40
#     |
# 169 |             | [0xfe, 0xed, 0xfa, 0xcf, ..]
#     |                                        ^^
#     |
#     = note: for more information, see https://github.com/rust-lang/rust/issues/62254

# error[E0658]: subslice patterns are unstable
#    --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/object-0.23.0/src/read/mod.rs:170:40
#     |
# 170 |             | [0xcf, 0xfa, 0xed, 0xfe, ..] => FileKind::MachO64,
#     |                                        ^^
#     |
#     = note: for more information, see https://github.com/rust-lang/rust/issues/62254

# error[E0658]: subslice patterns are unstable
#    --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/object-0.23.0/src/read/mod.rs:172:38
#     |
# 172 |             [0xca, 0xfe, 0xba, 0xbe, ..] => FileKind::MachOFat32,
#     |                                      ^^
#     |
#     = note: for more information, see https://github.com/rust-lang/rust/issues/62254

# error[E0658]: subslice patterns are unstable
#    --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/object-0.23.0/src/read/mod.rs:174:38
#     |
# 174 |             [0xca, 0xfe, 0xba, 0xbf, ..] => FileKind::MachOFat64,
#     |                                      ^^
#     |
#     = note: for more information, see https://github.com/rust-lang/rust/issues/62254

# error[E0658]: subslice patterns are unstable
#    --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/object-0.23.0/src/read/mod.rs:178:26
#     |
# 178 |             [b'M', b'Z', ..] => {
#     |                          ^^
#     |
#     = note: for more information, see https://github.com/rust-lang/rust/issues/62254

# error[E0658]: subslice patterns are unstable
#    --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/object-0.23.0/src/read/mod.rs:194:26
#     |
# 194 |             [0x4c, 0x01, ..]
#     |                          ^^
#     |
#     = note: for more information, see https://github.com/rust-lang/rust/issues/62254

# error[E0658]: subslice patterns are unstable
#    --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/object-0.23.0/src/read/mod.rs:196:28
#     |
# 196 |             | [0x64, 0x86, ..] => FileKind::Coff,
#     |                            ^^
#     |
#     = note: for more information, see https://github.com/rust-lang/rust/issues/62254
