pub const ENABLE_PROVIDERS_ENV_NAME: &str = "ENABLE_PROVIDERS";
pub const ENABLE_CLEANING_WARNING_LOGS_DIRECTORY_ENV_NAME: &str = "ENABLE_CLEANING_WARNING_LOGS_DIRECTORY";
pub const ENABLE_CLEANING_WARNING_LOGS_DB_IN_MONGO_ENV_NAME: &str = "ENABLE_CLEANING_WARNING_LOGS_DB_IN_MONGO";
pub const ENABLE_CLEANING_WARNING_LOGS_DB_COLLECTIONS_IN_MONGO_ENV_NAME: &str = "ENABLE_CLEANING_WARNING_LOGS_DB_COLLECTIONS_IN_MONGO";
pub const ENABLE_TIME_MEASUREMENT_ENV_NAME: &str = "ENABLE_TIME_MEASUREMENT";
pub const ENABLE_PROVIDER_LINKS_LIMIT_ENV_NAME: &str = "ENABLE_PROVIDER_LINKS_LIMIT";
pub const ENABLE_COMMON_PROVIDERS_LINKS_LIMIT_ENV_NAME: &str = "ENABLE_COMMON_PROVIDERS_LINKS_LIMIT";
pub const ENABLE_RANDOMIZE_ORDER_FOR_PROVIDERS_LINK_PARTS_FOR_MONGO_ENV_NAME: &str = "ENABLE_RANDOMIZE_ORDER_FOR_PROVIDERS_LINK_PARTS_FOR_MONGO";
pub const ENABLE_PRINTS_ENV_NAME: &str = "ENABLE_PRINTS";
pub const ENABLE_ERROR_PRINTS_ENV_NAME: &str = "ENABLE_ERROR_PRINTS";
pub const ENABLE_WARNING_HIGH_PRINTS_ENV_NAME: &str = "ENABLE_WARNING_HIGH_PRINTS";
pub const ENABLE_WARNING_LOW_PRINTS_ENV_NAME: &str = "ENABLE_WARNING_LOW_PRINTS";
pub const ENABLE_SUCCESS_PRINTS_ENV_NAME: &str = "ENABLE_SUCCESS_PRINTS";
pub const ENABLE_PARTIAL_SUCCESS_PRINTS_ENV_NAME: &str = "ENABLE_PARTIAL_SUCCESS_PRINTS";
pub const ENABLE_TIME_MEASUREMENT_PRINTS_ENV_NAME: &str = "ENABLE_TIME_MEASUREMENT_PRINTS";
pub const ENABLE_CLEANING_WARNING_LOGS_DIRECTORY_PRINTS_ENV_NAME: &str = "ENABLE_CLEANING_WARNING_LOGS_DIRECTORY_PRINTS";
pub const ENABLE_INFO_PRINTS_ENV_NAME: &str = "ENABLE_INFO_PRINTS";
pub const ENABLE_ALL_PROVIDERS_PRINTS_ENV_NAME: &str = "ENABLE_ALL_PROVIDERS_PRINTS";
pub const ENABLE_ERROR_PRINTS_FOR_ALL_PROVIDERS_ENV_NAME: &str = "ENABLE_ERROR_PRINTS_FOR_ALL_PROVIDERS";
pub const ENABLE_WARNING_HIGH_PRINTS_FOR_ALL_PROVIDERS_ENV_NAME: &str = "ENABLE_WARNING_HIGH_PRINTS_FOR_ALL_PROVIDERS";
pub const ENABLE_WARNING_LOW_PRINTS_FOR_ALL_PROVIDERS_ENV_NAME: &str = "ENABLE_WARNING_LOW_PRINTS_FOR_ALL_PROVIDERS";
pub const ENABLE_SUCCESS_PRINTS_FOR_ALL_PROVIDERS_ENV_NAME: &str = "ENABLE_SUCCESS_PRINTS_FOR_ALL_PROVIDERS";
pub const ENABLE_PARTIAL_SUCCESS_PRINTS_FOR_ALL_PROVIDERS_ENV_NAME: &str = "ENABLE_PARTIAL_SUCCESS_PRINTS_FOR_ALL_PROVIDERS";
pub const ENABLE_TIME_MEASUREMENT_PRINTS_FOR_ALL_PROVIDERS_ENV_NAME: &str = "ENABLE_TIME_MEASUREMENT_PRINTS_FOR_ALL_PROVIDERS";
pub const ENABLE_CLEANING_WARNING_LOGS_DIRECTORY_PRINTS_FOR_ALL_PROVIDERS_ENV_NAME: &str = "ENABLE_CLEANING_WARNING_LOGS_DIRECTORY_PRINTS_FOR_ALL_PROVIDERS";
pub const ENABLE_INFO_PRINTS_FOR_ALL_PROVIDERS_ENV_NAME: &str = "ENABLE_INFO_PRINTS_FOR_ALL_PROVIDERS";
pub const ENABLE_WRITE_ERROR_LOGS_IN_LOCAL_FOLDER_ENV_NAME: &str = "ENABLE_WRITE_ERROR_LOGS_IN_LOCAL_FOLDER";
pub const ENABLE_WRITE_ERROR_LOGS_IN_MONGO_ENV_NAME: &str = "ENABLE_WRITE_ERROR_LOGS_IN_MONGO";
pub const ENABLE_INITIALIZE_MONGO_WITH_PROVIDERS_LINK_PARTS_ENV_NAME: &str = "ENABLE_INITIALIZE_MONGO_WITH_PROVIDERS_LINK_PARTS";

pub const ENABLE_INITIALIZE_MONGO_WITH_ARXIV_LINK_PARTS_ENV_NAME: &str = "ENABLE_INITIALIZE_MONGO_WITH_ARXIV_LINK_PARTS";
pub const ENABLE_INITIALIZE_MONGO_WITH_BIORXIV_LINK_PARTS_ENV_NAME: &str = "ENABLE_INITIALIZE_MONGO_WITH_BIORXIV_LINK_PARTS";
pub const ENABLE_INITIALIZE_MONGO_WITH_GITHUB_LINK_PARTS_ENV_NAME: &str = "ENABLE_INITIALIZE_MONGO_WITH_GITHUB_LINK_PARTS";
pub const ENABLE_INITIALIZE_MONGO_WITH_HABR_LINK_PARTS_ENV_NAME: &str = "ENABLE_INITIALIZE_MONGO_WITH_HABR_LINK_PARTS";
pub const ENABLE_INITIALIZE_MONGO_WITH_MEDRXIV_LINK_PARTS_ENV_NAME: &str = "ENABLE_INITIALIZE_MONGO_WITH_MEDRXIV_LINK_PARTS";
pub const ENABLE_INITIALIZE_MONGO_WITH_REDDIT_LINK_PARTS_ENV_NAME: &str = "ENABLE_INITIALIZE_MONGO_WITH_REDDIT_LINK_PARTS";
pub const ENABLE_INITIALIZE_MONGO_WITH_TWITTER_LINK_PARTS_ENV_NAME: &str = "ENABLE_INITIALIZE_MONGO_WITH_TWITTER_LINK_PARTS";

pub const ENABLE_ARXIV_ENV_NAME: &str = "ENABLE_ARXIV";
pub const ENABLE_BIORXIV_ENV_NAME: &str = "ENABLE_BIORXIV";
pub const ENABLE_GITHUB_ENV_NAME: &str = "ENABLE_GITHUB";
pub const ENABLE_HABR_ENV_NAME: &str = "ENABLE_HABR";
pub const ENABLE_MEDRXIV_ENV_NAME: &str = "ENABLE_MEDRXIV";
pub const ENABLE_REDDIT_ENV_NAME: &str = "ENABLE_REDDIT";
pub const ENABLE_TWITTER_ENV_NAME: &str = "ENABLE_TWITTER";

pub const ENABLE_PRINTS_ARXIV_ENV_NAME: &str = "ENABLE_PRINTS_ARXIV";
pub const ENABLE_PRINTS_BIORXIV_ENV_NAME: &str = "ENABLE_PRINTS_BIORXIV";
pub const ENABLE_PRINTS_GITHUB_ENV_NAME: &str = "ENABLE_PRINTS_GITHUB";
pub const ENABLE_PRINTS_HABR_ENV_NAME: &str = "ENABLE_PRINTS_HABR";
pub const ENABLE_PRINTS_MEDRXIV_ENV_NAME: &str = "ENABLE_PRINTS_MEDRXIV";
pub const ENABLE_PRINTS_REDDIT_ENV_NAME: &str = "ENABLE_PRINTS_REDDIT";
pub const ENABLE_PRINTS_TWITTER_ENV_NAME: &str = "ENABLE_PRINTS_TWITTER";

pub const ENABLE_WARNING_HIGH_PRINTS_FOR_ARXIV_ENV_NAME: &str = "ENABLE_WARNING_HIGH_PRINTS_FOR_ARXIV";
pub const ENABLE_WARNING_HIGH_PRINTS_FOR_BIORXIV_ENV_NAME: &str = "ENABLE_WARNING_HIGH_PRINTS_FOR_BIORXIV";
pub const ENABLE_WARNING_HIGH_PRINTS_FOR_GITHUB_ENV_NAME: &str = "ENABLE_WARNING_HIGH_PRINTS_FOR_GITHUB";
pub const ENABLE_WARNING_HIGH_PRINTS_FOR_HABR_ENV_NAME: &str = "ENABLE_WARNING_HIGH_PRINTS_FOR_HABR";
pub const ENABLE_WARNING_HIGH_PRINTS_FOR_MEDRXIV_ENV_NAME: &str = "ENABLE_WARNING_HIGH_PRINTS_FOR_MEDRXIV";
pub const ENABLE_WARNING_HIGH_PRINTS_FOR_REDDIT_ENV_NAME: &str = "ENABLE_WARNING_HIGH_PRINTS_FOR_REDDIT";
pub const ENABLE_WARNING_HIGH_PRINTS_FOR_TWITTER_ENV_NAME: &str = "ENABLE_WARNING_HIGH_PRINTS_FOR_TWITTER";

pub const ENABLE_WARNING_LOW_PRINTS_FOR_ARXIV_ENV_NAME: &str = "ENABLE_WARNING_LOW_PRINTS_FOR_ARXIV";
pub const ENABLE_WARNING_LOW_PRINTS_FOR_BIORXIV_ENV_NAME: &str = "ENABLE_WARNING_LOW_PRINTS_FOR_BIORXIV";
pub const ENABLE_WARNING_LOW_PRINTS_FOR_GITHUB_ENV_NAME: &str = "ENABLE_WARNING_LOW_PRINTS_FOR_GITHUB";
pub const ENABLE_WARNING_LOW_PRINTS_FOR_HABR_ENV_NAME: &str = "ENABLE_WARNING_LOW_PRINTS_FOR_HABR";
pub const ENABLE_WARNING_LOW_PRINTS_FOR_MEDRXIV_ENV_NAME: &str = "ENABLE_WARNING_LOW_PRINTS_FOR_MEDRXIV";
pub const ENABLE_WARNING_LOW_PRINTS_FOR_REDDIT_ENV_NAME: &str = "ENABLE_WARNING_LOW_PRINTS_FOR_REDDIT";
pub const ENABLE_WARNING_LOW_PRINTS_FOR_TWITTER_ENV_NAME: &str = "ENABLE_WARNING_LOW_PRINTS_FOR_TWITTER";

pub const ENABLE_ERROR_PRINTS_FOR_ARXIV_ENV_NAME: &str = "ENABLE_ERROR_PRINTS_FOR_ARXIV";
pub const ENABLE_ERROR_PRINTS_FOR_BIORXIV_ENV_NAME: &str = "ENABLE_ERROR_PRINTS_FOR_BIORXIV";
pub const ENABLE_ERROR_PRINTS_FOR_GITHUB_ENV_NAME: &str = "ENABLE_ERROR_PRINTS_FOR_GITHUB";
pub const ENABLE_ERROR_PRINTS_FOR_HABR_ENV_NAME: &str = "ENABLE_ERROR_PRINTS_FOR_HABR";
pub const ENABLE_ERROR_PRINTS_FOR_MEDRXIV_ENV_NAME: &str = "ENABLE_ERROR_PRINTS_FOR_MEDRXIV";
pub const ENABLE_ERROR_PRINTS_FOR_REDDIT_ENV_NAME: &str = "ENABLE_ERROR_PRINTS_FOR_REDDIT";
pub const ENABLE_ERROR_PRINTS_FOR_TWITTER_ENV_NAME: &str = "ENABLE_ERROR_PRINTS_FOR_TWITTER";

pub const ENABLE_SUCCESS_PRINTS_FOR_ARXIV_ENV_NAME: &str = "ENABLE_SUCCESS_PRINTS_FOR_ARXIV";
pub const ENABLE_SUCCESS_PRINTS_FOR_BIORXIV_ENV_NAME: &str = "ENABLE_SUCCESS_PRINTS_FOR_BIORXIV";
pub const ENABLE_SUCCESS_PRINTS_FOR_GITHUB_ENV_NAME: &str = "ENABLE_SUCCESS_PRINTS_FOR_GITHUB";
pub const ENABLE_SUCCESS_PRINTS_FOR_HABR_ENV_NAME: &str = "ENABLE_SUCCESS_PRINTS_FOR_HABR";
pub const ENABLE_SUCCESS_PRINTS_FOR_MEDRXIV_ENV_NAME: &str = "ENABLE_SUCCESS_PRINTS_FOR_MEDRXIV";
pub const ENABLE_SUCCESS_PRINTS_FOR_REDDIT_ENV_NAME: &str = "ENABLE_SUCCESS_PRINTS_FOR_REDDIT";
pub const ENABLE_SUCCESS_PRINTS_FOR_TWITTER_ENV_NAME: &str = "ENABLE_SUCCESS_PRINTS_FOR_TWITTER";

pub const ENABLE_PARTIAL_SUCCESS_PRINTS_FOR_ARXIV_ENV_NAME: &str = "ENABLE_PARTIAL_SUCCESS_PRINTS_FOR_ARXIV";
pub const ENABLE_PARTIAL_SUCCESS_PRINTS_FOR_BIORXIV_ENV_NAME: &str = "ENABLE_PARTIAL_SUCCESS_PRINTS_FOR_BIORXIV";
pub const ENABLE_PARTIAL_SUCCESS_PRINTS_FOR_GITHUB_ENV_NAME: &str = "ENABLE_PARTIAL_SUCCESS_PRINTS_FOR_GITHUB";
pub const ENABLE_PARTIAL_SUCCESS_PRINTS_FOR_HABR_ENV_NAME: &str = "ENABLE_PARTIAL_SUCCESS_PRINTS_FOR_HABR";
pub const ENABLE_PARTIAL_SUCCESS_PRINTS_FOR_MEDRXIV_ENV_NAME: &str = "ENABLE_PARTIAL_SUCCESS_PRINTS_FOR_MEDRXIV";
pub const ENABLE_PARTIAL_SUCCESS_PRINTS_FOR_REDDIT_ENV_NAME: &str = "ENABLE_PARTIAL_SUCCESS_PRINTS_FOR_REDDIT";
pub const ENABLE_PARTIAL_SUCCESS_PRINTS_FOR_TWITTER_ENV_NAME: &str = "ENABLE_PARTIAL_SUCCESS_PRINTS_FOR_TWITTER";

pub const ENABLE_CLEANING_WARNING_LOGS_DIRECTORY_FOR_ARXIV_ENV_NAME: &str = "ENABLE_CLEANING_WARNING_LOGS_DIRECTORY_FOR_ARXIV";
pub const ENABLE_CLEANING_WARNING_LOGS_DIRECTORY_FOR_BIORXIV_ENV_NAME: &str = "ENABLE_CLEANING_WARNING_LOGS_DIRECTORY_FOR_BIORXIV";
pub const ENABLE_CLEANING_WARNING_LOGS_DIRECTORY_FOR_GITHUB_ENV_NAME: &str = "ENABLE_CLEANING_WARNING_LOGS_DIRECTORY_FOR_GITHUB";
pub const ENABLE_CLEANING_WARNING_LOGS_DIRECTORY_FOR_HABR_ENV_NAME: &str = "ENABLE_CLEANING_WARNING_LOGS_DIRECTORY_FOR_HABR";
pub const ENABLE_CLEANING_WARNING_LOGS_DIRECTORY_FOR_MEDRXIV_ENV_NAME: &str = "ENABLE_CLEANING_WARNING_LOGS_DIRECTORY_FOR_MEDRXIV";
pub const ENABLE_CLEANING_WARNING_LOGS_DIRECTORY_FOR_REDDIT_ENV_NAME: &str = "ENABLE_CLEANING_WARNING_LOGS_DIRECTORY_FOR_REDDIT";
pub const ENABLE_CLEANING_WARNING_LOGS_DIRECTORY_FOR_TWITTER_ENV_NAME: &str = "ENABLE_CLEANING_WARNING_LOGS_DIRECTORY_FOR_TWITTER";

pub const ENABLE_CLEANING_WARNING_LOGS_DB_IN_MONGO_FOR_ARXIV_ENV_NAME: &str = "ENABLE_CLEANING_WARNING_LOGS_DB_IN_MONGO_FOR_ARXIV";
pub const ENABLE_CLEANING_WARNING_LOGS_DB_IN_MONGO_FOR_BIORXIV_ENV_NAME: &str = "ENABLE_CLEANING_WARNING_LOGS_DB_IN_MONGO_FOR_BIORXIV";
pub const ENABLE_CLEANING_WARNING_LOGS_DB_IN_MONGO_FOR_GITHUB_ENV_NAME: &str = "ENABLE_CLEANING_WARNING_LOGS_DB_IN_MONGO_FOR_GITHUB";
pub const ENABLE_CLEANING_WARNING_LOGS_DB_IN_MONGO_FOR_HABR_ENV_NAME: &str = "ENABLE_CLEANING_WARNING_LOGS_DB_IN_MONGO_FOR_HABR";
pub const ENABLE_CLEANING_WARNING_LOGS_DB_IN_MONGO_FOR_MEDRXIV_ENV_NAME: &str = "ENABLE_CLEANING_WARNING_LOGS_DB_IN_MONGO_FOR_MEDRXIV";
pub const ENABLE_CLEANING_WARNING_LOGS_DB_IN_MONGO_FOR_REDDIT_ENV_NAME: &str = "ENABLE_CLEANING_WARNING_LOGS_DB_IN_MONGO_FOR_REDDIT";
pub const ENABLE_CLEANING_WARNING_LOGS_DB_IN_MONGO_FOR_TWITTER_ENV_NAME: &str = "ENABLE_CLEANING_WARNING_LOGS_DB_IN_MONGO_FOR_TWITTER";

pub const ENABLE_CLEANING_WARNING_LOGS_DB_COLLECTIONS_IN_MONGO_FOR_ARXIV_ENV_NAME: &str = "ENABLE_CLEANING_WARNING_LOGS_DB_COLLECTIONS_IN_MONGO_FOR_ARXIV";
pub const ENABLE_CLEANING_WARNING_LOGS_DB_COLLECTIONS_IN_MONGO_FOR_BIORXIV_ENV_NAME: &str = "ENABLE_CLEANING_WARNING_LOGS_DB_COLLECTIONS_IN_MONGO_FOR_BIORXIV";
pub const ENABLE_CLEANING_WARNING_LOGS_DB_COLLECTIONS_IN_MONGO_FOR_GITHUB_ENV_NAME: &str = "ENABLE_CLEANING_WARNING_LOGS_DB_COLLECTIONS_IN_MONGO_FOR_GITHUB";
pub const ENABLE_CLEANING_WARNING_LOGS_DB_COLLECTIONS_IN_MONGO_FOR_HABR_ENV_NAME: &str = "ENABLE_CLEANING_WARNING_LOGS_DB_COLLECTIONS_IN_MONGO_FOR_HABR";
pub const ENABLE_CLEANING_WARNING_LOGS_DB_COLLECTIONS_IN_MONGO_FOR_MEDRXIV_ENV_NAME: &str = "ENABLE_CLEANING_WARNING_LOGS_DB_COLLECTIONS_IN_MONGO_FOR_MEDRXIV";
pub const ENABLE_CLEANING_WARNING_LOGS_DB_COLLECTIONS_IN_MONGO_FOR_REDDIT_ENV_NAME: &str = "ENABLE_CLEANING_WARNING_LOGS_DB_COLLECTIONS_IN_MONGO_FOR_REDDIT";
pub const ENABLE_CLEANING_WARNING_LOGS_DB_COLLECTIONS_IN_MONGO_FOR_TWITTER_ENV_NAME: &str = "ENABLE_CLEANING_WARNING_LOGS_DB_COLLECTIONS_IN_MONGO_FOR_TWITTER";

pub const ENABLE_TIME_MEASUREMENT_FOR_ARXIV_ENV_NAME: &str = "ENABLE_TIME_MEASUREMENT_FOR_ARXIV";
pub const ENABLE_TIME_MEASUREMENT_FOR_BIORXIV_ENV_NAME: &str = "ENABLE_TIME_MEASUREMENT_FOR_BIORXIV";
pub const ENABLE_TIME_MEASUREMENT_FOR_GITHUB_ENV_NAME: &str = "ENABLE_TIME_MEASUREMENT_FOR_GITHUB";
pub const ENABLE_TIME_MEASUREMENT_FOR_HABR_ENV_NAME: &str = "ENABLE_TIME_MEASUREMENT_FOR_HABR";
pub const ENABLE_TIME_MEASUREMENT_FOR_MEDRXIV_ENV_NAME: &str = "ENABLE_TIME_MEASUREMENT_FOR_MEDRXIV";
pub const ENABLE_TIME_MEASUREMENT_FOR_REDDIT_ENV_NAME: &str = "ENABLE_TIME_MEASUREMENT_FOR_REDDIT";
pub const ENABLE_TIME_MEASUREMENT_FOR_TWITTER_ENV_NAME: &str = "ENABLE_TIME_MEASUREMENT_FOR_TWITTER";

pub const ENABLE_INFO_FOR_ARXIV_ENV_NAME: &str = "ENABLE_INFO_FOR_ARXIV";
pub const ENABLE_INFO_FOR_BIORXIV_ENV_NAME: &str = "ENABLE_INFO_FOR_BIORXIV";
pub const ENABLE_INFO_FOR_GITHUB_ENV_NAME: &str = "ENABLE_INFO_FOR_GITHUB";
pub const ENABLE_INFO_FOR_HABR_ENV_NAME: &str = "ENABLE_INFO_FOR_HABR";
pub const ENABLE_INFO_FOR_MEDRXIV_ENV_NAME: &str = "ENABLE_INFO_FOR_MEDRXIV";
pub const ENABLE_INFO_FOR_REDDIT_ENV_NAME: &str = "ENABLE_INFO_FOR_REDDIT";
pub const ENABLE_INFO_FOR_TWITTER_ENV_NAME: &str = "ENABLE_INFO_FOR_TWITTER";

pub const ENABLE_LINKS_LIMIT_FOR_ARXIV_ENV_NAME: &str = "ENABLE_LINKS_LIMIT_FOR_ARXIV";
pub const ENABLE_LINKS_LIMIT_FOR_BIORXIV_ENV_NAME: &str = "ENABLE_LINKS_LIMIT_FOR_BIORXIV";
pub const ENABLE_LINKS_LIMIT_FOR_GITHUB_ENV_NAME: &str = "ENABLE_LINKS_LIMIT_FOR_GITHUB";
pub const ENABLE_LINKS_LIMIT_FOR_HABR_ENV_NAME: &str = "ENABLE_LINKS_LIMIT_FOR_HABR";
pub const ENABLE_LINKS_LIMIT_FOR_MEDRXIV_ENV_NAME: &str = "ENABLE_LINKS_LIMIT_FOR_MEDRXIV";
pub const ENABLE_LINKS_LIMIT_FOR_REDDIT_ENV_NAME: &str = "ENABLE_LINKS_LIMIT_FOR_REDDIT";
pub const ENABLE_LINKS_LIMIT_FOR_TWITTER_ENV_NAME: &str = "ENABLE_LINKS_LIMIT_FOR_TWITTER";

pub const ENABLE_RANDOMIZE_ORDER_FOR_ARXIV_LINK_PARTS_FOR_MONGO_ENV_NAME: &str = "ENABLE_RANDOMIZE_ORDER_FOR_ARXIV_LINK_PARTS_FOR_MONGO";
pub const ENABLE_RANDOMIZE_ORDER_FOR_BIORXIV_LINK_PARTS_FOR_MONGO_ENV_NAME: &str = "ENABLE_RANDOMIZE_ORDER_FOR_BIORXIV_LINK_PARTS_FOR_MONGO";
pub const ENABLE_RANDOMIZE_ORDER_FOR_GITHUB_LINK_PARTS_FOR_MONGO_ENV_NAME: &str = "ENABLE_RANDOMIZE_ORDER_FOR_GITHUB_LINK_PARTS_FOR_MONGO";
pub const ENABLE_RANDOMIZE_ORDER_FOR_HABR_LINK_PARTS_FOR_MONGO_ENV_NAME: &str = "ENABLE_RANDOMIZE_ORDER_FOR_HABR_LINK_PARTS_FOR_MONGO";
pub const ENABLE_RANDOMIZE_ORDER_FOR_MEDRXIV_LINK_PARTS_FOR_MONGO_ENV_NAME: &str = "ENABLE_RANDOMIZE_ORDER_FOR_MEDRXIV_LINK_PARTS_FOR_MONGO";
pub const ENABLE_RANDOMIZE_ORDER_FOR_REDDIT_LINK_PARTS_FOR_MONGO_ENV_NAME: &str = "ENABLE_RANDOMIZE_ORDER_FOR_REDDIT_LINK_PARTS_FOR_MONGO";
pub const ENABLE_RANDOMIZE_ORDER_FOR_TWITTER_LINK_PARTS_FOR_MONGO_ENV_NAME: &str = "ENABLE_RANDOMIZE_ORDER_FOR_TWITTER_LINK_PARTS_FOR_MONGO";
