pub const GITHUB_NAME_ENV_NAME: &str = "GITHUB_NAME";
pub const GITHUB_TOKEN_ENV_NAME: &str = "GITHUB_TOKEN";

pub const REDDIT_USER_AGENT_ENV_NAME: &str = "REDDIT_USER_AGENT";
pub const REDDIT_CLIENT_ID_ENV_NAME: &str = "REDDIT_CLIENT_ID";
pub const REDDIT_CLIENT_SECRET_ENV_NAME: &str = "REDDIT_CLIENT_SECRET";
pub const REDDIT_USERNAME_ENV_NAME: &str = "REDDIT_USERNAME";
pub const REDDIT_PASSWORD_ENV_NAME: &str = "REDDIT_PASSWORD";

pub const STARTING_CHECK_LINK_ENV_NAME: &str = "STARTING_CHECK_LINK";
pub const USER_CREDENTIALS_DUMMY_HANDLE_ENV_NAME: &str = "USER_CREDENTIALS_DUMMY_HANDLE";
pub const WARNING_LOGS_DIRECTORY_NAME_ENV_NAME: &str = "WARNING_LOGS_DIRECTORY_NAME";
pub const UNHANDLED_SUCCESS_HANDLED_SUCCESS_ARE_THERE_ITEMS_INITIALIZED_POSTS_DIR_ENV_NAME: &str = "UNHANDLED_SUCCESS_HANDLED_SUCCESS_ARE_THERE_ITEMS_INITIALIZED_POSTS_DIR";

pub const PROVIDERS_DB_NAME_HANDLE_ENV_NAME: &str = "PROVIDERS_DB_NAME_HANDLE";
pub const PROVIDERS_DB_COLLECTION_HANDLE_SECOND_PART_ENV_NAME: &str = "PROVIDERS_DB_COLLECTION_HANDLE_SECOND_PART";
pub const PROVIDERS_DB_COLLECTION_DOCUMENT_FIELD_NAME_HANDLE_ENV_NAME: &str = "PROVIDERS_DB_COLLECTION_DOCUMENT_FIELD_NAME_HANDLE";
pub const PATH_TO_PROVIDER_LINK_PARTS_FOLDER_ENV_NAME: &str = "PATH_TO_PROVIDER_LINK_PARTS_FOLDER";
pub const LOG_FILE_EXTENSION_ENV_NAME: &str = "LOG_FILE_EXTENSION";
pub const DB_PROVIDERS_LOGS_NAME_HANDLE_ENV_NAME: &str = "DB_PROVIDERS_LOGS_NAME_HANDLE";
pub const DB_PROVIDERS_LOGS_COLLECTION_HANDLE_SECOND_PART_ENV_NAME: &str = "DB_PROVIDERS_LOGS_COLLECTION_HANDLE_SECOND_PART";
pub const DB_PROVIDERS_LOGS_COLLECTION_DOCUMENT_FIELD_NAME_HANDLE_ENV_NAME: &str = "DB_PROVIDERS_LOGS_COLLECTION_DOCUMENT_FIELD_NAME_HANDLE";

pub const MONGO_FIRST_HANDLE_URL_PART_ENV_NAME: &str = "MONGO_FIRST_HANDLE_URL_PART";
pub const MONGO_SECOND_HANDLE_URL_PART_ENV_NAME: &str = "MONGO_SECOND_HANDLE_URL_PART";
pub const MONGO_THIRD_HANDLE_URL_PART_ENV_NAME: &str = "MONGO_THIRD_HANDLE_URL_PART";
pub const MONGO_FOURTH_HANDLE_URL_PART_ENV_NAME: &str = "MONGO_FOURTH_HANDLE_URL_PART";
pub const MONGO_FIFTH_HANDLE_URL_PART_ENV_NAME: &str = "MONGO_FIFTH_HANDLE_URL_PART";

pub const MONGO_LOGIN_ENV_NAME: &str = "MONGO_LOGIN";
pub const MONGO_PASSWORD_ENV_NAME: &str = "MONGO_PASSWORD";
pub const MONGO_IP_ENV_NAME: &str = "MONGO_IP";
pub const MONGO_PORT_ENV_NAME: &str = "MONGO_PORT";
pub const MONGO_PARAMS_ENV_NAME: &str = "MONGO_PARAMS";

pub const POSTGRES_FIRST_HANDLE_URL_PART_ENV_NAME: &str = "POSTGRES_FIRST_HANDLE_URL_PART";
pub const POSTGRES_SECOND_HANDLE_URL_PART_ENV_NAME: &str = "POSTGRES_SECOND_HANDLE_URL_PART";
pub const POSTGRES_THIRD_HANDLE_URL_PART_ENV_NAME: &str = "POSTGRES_THIRD_HANDLE_URL_PART";
pub const POSTGRES_FOURTH_HANDLE_URL_PART_ENV_NAME: &str = "POSTGRES_FOURTH_HANDLE_URL_PART";
pub const POSTGRES_FIFTH_HANDLE_URL_PART_ENV_NAME: &str = "POSTGRES_FIFTH_HANDLE_URL_PART";

pub const POSTGRES_LOGIN_ENV_NAME: &str = "POSTGRES_LOGIN";
pub const POSTGRES_PASSWORD_ENV_NAME: &str = "POSTGRES_PASSWORD";
pub const POSTGRES_IP_ENV_NAME: &str = "POSTGRES_IP";
pub const POSTGRES_PORT_ENV_NAME: &str = "POSTGRES_PORT";
pub const POSTGRES_DB_ENV_NAME: &str = "POSTGRES_DB";

pub const ARXIV_LINK_ENV_NAME: &str = "ARXIV_LINK";
pub const BIORXIV_LINK_ENV_NAME: &str = "BIORXIV_LINK";
pub const GITHUB_LINK_ENV_NAME: &str = "GITHUB_LINK";
pub const HABR_LINK_ENV_NAME: &str = "HABR_LINK";
pub const MEDRXIV_LINK_ENV_NAME: &str = "MEDRXIV_LINK";
pub const REDDIT_LINK_ENV_NAME: &str = "REDDIT_LINK";
pub const TWITTER_LINK_ENV_NAME: &str = "TWITTER_LINK";