pub const COMMON_PROVIDERS_LINKS_LIMIT_ENV_NAME: &str = "COMMON_PROVIDERS_LINKS_LIMIT";

pub const LINKS_LIMIT_FOR_ARXIV_ENV_NAME: &str = "LINKS_LIMIT_FOR_ARXIV";
pub const LINKS_LIMIT_FOR_BIORXIV_ENV_NAME: &str = "LINKS_LIMIT_FOR_BIORXIV";
pub const LINKS_LIMIT_FOR_GITHUB_ENV_NAME: &str = "LINKS_LIMIT_FOR_GITHUB";
pub const LINKS_LIMIT_FOR_HABR_ENV_NAME: &str = "LINKS_LIMIT_FOR_HABR";
pub const LINKS_LIMIT_FOR_MEDRXIV_ENV_NAME: &str = "LINKS_LIMIT_FOR_MEDRXIV";
pub const LINKS_LIMIT_FOR_REDDIT_ENV_NAME: &str = "LINKS_LIMIT_FOR_REDDIT";
pub const LINKS_LIMIT_FOR_TWITTER_ENV_NAME: &str = "LINKS_LIMIT_FOR_TWITTER";