use std::collections::HashMap;

pub fn get_arxiv_links_in_hash_map() -> HashMap<&'static str, String> {
    let arxiv_rss_link = "http://export.arxiv.org/rss/".to_string();
    let arxiv_sections_links: HashMap<&str,String> =
    //Astrophysics
    [("Cosmology and Nongalactic Astrophysics", "astro-ph.CO".to_string() +  &arxiv_rss_link),
     ("Earth and Planetary Astrophysics", "astro-ph.EP".to_string() +  &arxiv_rss_link),
     ("Astrophysics of Galaxies", "astro-ph.GA".to_string() + &arxiv_rss_link),
     ("High Energy Astrophysical Phenomena", "astro-ph.HE".to_string() + &arxiv_rss_link),
     ("Instrumentation and Methods for Astrophysics", "astro-ph.IM".to_string() + &arxiv_rss_link),
     ("Solar and Stellar Astrophysics", "astro-ph.SR".to_string() + &arxiv_rss_link),
     //Condensed Matter
     ("Disordered Systems and Neural Networks", "cond-mat.dis-nn".to_string() + &arxiv_rss_link),
     ("Mesoscale and Nanoscale Physics", "cond-mat.mes-hall".to_string() + &arxiv_rss_link),
     ("Materials Science", "cond-mat.mtrl-sci".to_string() + &arxiv_rss_link),
     ("Other Condensed Matter", "cond-mat.other".to_string() + &arxiv_rss_link),//НАДО ЛИ - УПАДЕТ ЖЕ 
     ("Quantum Gases", "cond-mat.quant-gas".to_string() + &arxiv_rss_link),
     ("Soft Condensed Matter", "cond-mat.soft".to_string() + &arxiv_rss_link),
     ("Statistical Mechanics", "cond-mat.stat-mech".to_string() + &arxiv_rss_link),
     ("Strongly Correlated Electrons", "cond-mat.str-el".to_string() + &arxiv_rss_link),
     ("Superconductivity", "cond-mat.supr-con".to_string() + &arxiv_rss_link),
     //Computer Science
     ("Artificial Intelligence", "cs.AI".to_string() + &arxiv_rss_link),
     ("Hardware Architecture", "cs.AR".to_string() + &arxiv_rss_link),
     ("Computational Complexity", "cs.CC".to_string() + &arxiv_rss_link),
     ("Computational Engineering, Finance, and Science", "cs.CE".to_string() + &arxiv_rss_link),
     ("Computational Geometry", "cs.CG".to_string() + &arxiv_rss_link),
     ("Computation and Language", "cs.CL".to_string() + &arxiv_rss_link),
     ("Cryptography and Security", "cs.CR".to_string() + &arxiv_rss_link),
     ("Computer Vision and Pattern Recognition", "cs.CV".to_string() + &arxiv_rss_link),
     ("Computers and Society", "cs.CY".to_string() + &arxiv_rss_link),
     ("Databases", "cs.DB".to_string() + &arxiv_rss_link),
     ("Distributed, Parallel, and Cluster Computing", "cs.DC".to_string() + &arxiv_rss_link),
     ("Digital Libraries", "cs.DL".to_string() + &arxiv_rss_link),
     ("Discrete Mathematics", "cs.DM".to_string() + &arxiv_rss_link),
     ("Data Structures and Algorithms", "cs.DS".to_string() + &arxiv_rss_link),
     ("Emerging Technologies", "cs.ET".to_string() + &arxiv_rss_link),
     ("Formal Languages and Automata Theory", "cs.FL".to_string() + &arxiv_rss_link),
     ("General Literature", "cs.GL".to_string() + &arxiv_rss_link),
     ("Graphics", "cs.GR".to_string() + &arxiv_rss_link),
     ("Computer Science and Game Theory", "cs.GT".to_string() + &arxiv_rss_link),
     ("Human-Computer Interaction", "cs.HC".to_string() + &arxiv_rss_link),
     ("Information Retrieval", "cs.IR".to_string() + &arxiv_rss_link),
     ("Information Theory", "cs.IT".to_string() + &arxiv_rss_link),
     ("Machine Learning", "cs.LG".to_string() + &arxiv_rss_link),
     ("Logic in Computer Science", "cs.LO".to_string() + &arxiv_rss_link),
     ("Multiagent Systems", "cs.MA".to_string() + &arxiv_rss_link),
     ("Multimedia", "cs.MM".to_string() + &arxiv_rss_link),
     ("Mathematical Software", "cs.MS".to_string() + &arxiv_rss_link),
     ("Numerical Analysis", "cs.NA".to_string() + &arxiv_rss_link),
     ("Neural and Evolutionary Computing", "cs.NE".to_string() + &arxiv_rss_link),
     ("Networking and Internet Architecture", "cs.NI".to_string() + &arxiv_rss_link),
     ("Other Computer Science", "cs.OH".to_string() + &arxiv_rss_link),
     ("Operating Systems", "cs.OS".to_string() + &arxiv_rss_link),
     ("Performance", "cs.PF".to_string() + &arxiv_rss_link),
     ("Programming Languages", "cs.PL".to_string() + &arxiv_rss_link),
     ("Robotics", "cs.RO".to_string() + &arxiv_rss_link),
     ("Sound", "cs.SC".to_string() + &arxiv_rss_link),
     ("Sound", "cs.SD".to_string() + &arxiv_rss_link),
     ("Software Engineering", "cs.SE".to_string() + &arxiv_rss_link),
     ("Social and Information Networks", "cs.SI".to_string() + &arxiv_rss_link),
     ("Systems and Control", "cs.SY".to_string() + &arxiv_rss_link),
     //Electrical Engineering and Systems Science
     ("Audio and Speech Processing", "eess.AS".to_string() + &arxiv_rss_link),
     ("Image and Video Processing", "eess.IV".to_string() + &arxiv_rss_link),
     ("Signal Processing", "eess.SP".to_string() + &arxiv_rss_link),
     ("Systems and Control", "eess.SY".to_string() + &arxiv_rss_link),
     //Mathematics
     ("Commutative Algebra", "math.AC".to_string() + &arxiv_rss_link),
     ("Algebraic Geometry", "math.AG".to_string() + &arxiv_rss_link),
     ("Analysis of PDEs", "math.AP".to_string() + &arxiv_rss_link),
     ("Algebraic Topology", "math.AT".to_string() + &arxiv_rss_link),
     ("Classical Analysis and ODEs", "math.CA".to_string() + &arxiv_rss_link),
     ("Combinatorics", "math.CO".to_string() + &arxiv_rss_link),
     ("Category Theory", "math.CT".to_string() + &arxiv_rss_link),
     ("Complex Variables", "math.CV".to_string() + &arxiv_rss_link),
     ("Differential Geometry", "math.DG".to_string() + &arxiv_rss_link),
     ("Dynamical Systems", "math.DS".to_string() + &arxiv_rss_link),
     ("Functional Analysis", "math.FA".to_string() + &arxiv_rss_link),
     ("General Mathematics", "math.GM".to_string() + &arxiv_rss_link),
     ("General Topology", "math.GN".to_string() + &arxiv_rss_link),
     ("Group Theory", "math.GR".to_string() + &arxiv_rss_link),
     ("Geometric Topology", "math.GT".to_string() + &arxiv_rss_link),
     ("History and Overview", "math.HO".to_string() + &arxiv_rss_link),
     ("Information Theory", "math.IT".to_string() + &arxiv_rss_link),
     ("K-Theory and Homology", "math.KT".to_string() + &arxiv_rss_link),
     ("Logic", "math.LO".to_string() + &arxiv_rss_link),
     ("Metric Geometry", "math.MG".to_string() + &arxiv_rss_link),
     ("Mathematical Physics", "math.MP".to_string() + &arxiv_rss_link),
     ("Numerical Analysis", "math.NA".to_string() + &arxiv_rss_link),
     ("Number Theory", "math.NT".to_string() + &arxiv_rss_link),
     ("Operator Algebras", "math.OA".to_string() + &arxiv_rss_link),
     ("Optimization and Control", "math.OC".to_string() + &arxiv_rss_link),
     ("Probability", "math.PR".to_string() + &arxiv_rss_link),
     ("Quantum Algebra", "math.QA".to_string() + &arxiv_rss_link),
     ("Rings and Algebras", "math.RA".to_string() + &arxiv_rss_link),
     ("Representation Theory", "math.RT".to_string() + &arxiv_rss_link),
     ("Symplectic Geometry", "math.SG".to_string() + &arxiv_rss_link),
     ("Spectral Theory", "math.SP".to_string() + &arxiv_rss_link),
     ("Statistics Theory", "math.ST".to_string() + &arxiv_rss_link),
     //Nonlinear Sciences
     ("Adaptation and Self-Organizing System", "nlin.AO".to_string() + &arxiv_rss_link),
     ("Chaotic Dynamics", "nlin.CD".to_string() + &arxiv_rss_link),
     ("Cellular Automata and Lattice Gases", "nlin.CG".to_string() + &arxiv_rss_link),
     ("Pattern Formation and Solitons", "nlin.PS".to_string() + &arxiv_rss_link),
     ("Exactly Solvable and Integrable Systems", "nlin.SI".to_string() + &arxiv_rss_link),
     //physics
     ("Accelerator Physics", "physics.acc-ph".to_string() + &arxiv_rss_link),
     ("Atmospheric and Oceanic Physics", "physics.ao-ph".to_string() + &arxiv_rss_link),
     ("Applied Physics", "physics.app-ph".to_string() + &arxiv_rss_link),
     ("Atomic and Molecular Clusters", "physics.atm-clus".to_string() + &arxiv_rss_link),
     ("Atomic Physics", "physics.atom-ph".to_string() + &arxiv_rss_link),
     ("Biological Physics", "physics.bio-ph".to_string() + &arxiv_rss_link),
     ("Chemical Physics", "physics.chem-ph".to_string() + &arxiv_rss_link),
     ("Classical Physics", "physics.class-ph".to_string() + &arxiv_rss_link),
     ("Computational Physics", "physics.comp-ph".to_string() + &arxiv_rss_link),
     ("Data Analysis, Statistics and Probability", "physics.data-an".to_string() + &arxiv_rss_link),
     ("Physics Education", "physics.ed-ph".to_string() + &arxiv_rss_link),
     ("Fluid Dynamics", "physics.flu-dyn".to_string() + &arxiv_rss_link),
     ("General Physics", "physics.gen-ph".to_string() + &arxiv_rss_link),
     ("Geophysics", "physics.geo-ph".to_string() + &arxiv_rss_link),
     ("History and Philosophy of Physics", "physics.hist-ph".to_string() + &arxiv_rss_link),
     ("Instrumentation and Detectors", "physics.ins-det".to_string() + &arxiv_rss_link),
     ("Medical Physics", "physics.med-ph".to_string() + &arxiv_rss_link),
     ("Optics", "physics.optics".to_string() + &arxiv_rss_link),
     ("Plasma Physics", "physics.plasm-ph".to_string() + &arxiv_rss_link),
     ("Popular Physics", "physics.pop-ph".to_string() + &arxiv_rss_link),
     ("Physics and Society", "physics.soc-ph".to_string() + &arxiv_rss_link),
     ("Space Physics", "physics.space-ph".to_string() + &arxiv_rss_link),
     //Quantitative Biology
     ("Biomolecules", "q-bio.BM".to_string() + &arxiv_rss_link),
     ("Cell Behavior", "q-bio.CB".to_string() + &arxiv_rss_link),
     ("Genomics", "q-bio.GN".to_string() + &arxiv_rss_link),
     ("Molecular Networks", "q-bio.MN".to_string() + &arxiv_rss_link),
     ("Neurons and Cognition", "q-bio.NC".to_string() + &arxiv_rss_link),
     ("Other Quantitative Biology", "q-bio.OT".to_string() + &arxiv_rss_link),
     ("Populations and Evolution", "q-bio.PE".to_string() + &arxiv_rss_link),
     ("Quantitative Methods", "q-bio.QM".to_string() + &arxiv_rss_link),
     ("Subcellular Processes", "q-bio.SC".to_string() + &arxiv_rss_link),
     ("Tissues and Organ", "q-bio.TO".to_string() + &arxiv_rss_link),
     //Statistics
     ("General Relativity and Quantum Cosmology", "gr-qc".to_string() + &arxiv_rss_link),
     ("High Energy Physics - Experiment", "hep-ex".to_string() + &arxiv_rss_link),
     ("High Energy Physics - Lattice", "hep-lat".to_string() + &arxiv_rss_link),
     ("High Energy Physics - Phenomenolog", "hep-ph".to_string() + &arxiv_rss_link),
     ("High Energy Physics - Theory", "hep-th".to_string() + &arxiv_rss_link),
     ("Quantum Physics", "quant-ph".to_string() + &arxiv_rss_link),
     ("Nuclear Experiment", "nucl-ex".to_string() + &arxiv_rss_link),
     ("Nuclear Theory", "nucl-th".to_string() + &arxiv_rss_link),
     ("Mathematical Physic", "math-ph".to_string() + &arxiv_rss_link),
     ]
     .iter().cloned().collect();
    arxiv_sections_links
}
