use std::collections::HashMap;

pub fn get_arxiv_links_in_hash_map() -> HashMap<&'static str, &'static str> {
    let arxiv_rss_link = "http://export.arxiv.org/rss/".to_string();
    let arxiv_sections_links: HashMap<&str,&str> =
    //Astrophysics
    [("Cosmology and Nongalactic Astrophysics", arxiv_rss_link + &"astro-ph.CO".to_string()),
     ("Earth and Planetary Astrophysics", arxiv_rss_link + &"astro-ph.EP".to_string()),
     ("Astrophysics of Galaxies", arxiv_rss_link + &"astro-ph.GA".to_string())
     ("High Energy Astrophysical Phenomena", arxiv_rss_link + &"astro-ph.HE".to_string())
     ("Instrumentation and Methods for Astrophysics", arxiv_rss_link + &"astro-ph.IM".to_string())
     ("Solar and Stellar Astrophysics", arxiv_rss_link + &"astro-ph.SR".to_string())
     //Condensed Matter
     ("Disordered Systems and Neural Networks", arxiv_rss_link + &"cond-mat.dis-nn".to_string())
     ("Mesoscale and Nanoscale Physics", arxiv_rss_link + &"cond-mat.mes-hall".to_string())
     ("Materials Science", arxiv_rss_link + &"cond-mat.mtrl-sci".to_string())
     ("Other Condensed Matter", arxiv_rss_link + &"cond-mat.other".to_string())//НАДО ЛИ - УПАДЕТ ЖЕ 
     ("Quantum Gases", arxiv_rss_link + &"cond-mat.quant-gas".to_string())
     ("Soft Condensed Matter", arxiv_rss_link + &"cond-mat.soft".to_string())
     ("Statistical Mechanics", arxiv_rss_link + &"cond-mat.stat-mech".to_string())
     ("Strongly Correlated Electrons", arxiv_rss_link + &"cond-mat.str-el".to_string())
     ("Superconductivity", arxiv_rss_link + &"cond-mat.supr-con".to_string())
     //Computer Science
     ("Artificial Intelligence", arxiv_rss_link + &"cs.AI".to_string())
     ("Hardware Architecture", arxiv_rss_link + &"cs.AR".to_string())
     ("Computational Complexity", arxiv_rss_link + &"cs.CC".to_string())
     ("Computational Engineering, Finance, and Science", arxiv_rss_link + &"cs.CE".to_string())
     ("Computational Geometry", arxiv_rss_link + &"cs.CG".to_string())
     ("Computation and Language", arxiv_rss_link + &"cs.CL".to_string())
     ("Cryptography and Security", arxiv_rss_link + &"cs.CR".to_string())
     ("Computer Vision and Pattern Recognition", arxiv_rss_link + &"cs.CV".to_string())
     ("Computers and Society", arxiv_rss_link + &"cs.CY".to_string())
     ("Databases", arxiv_rss_link + &"cs.DB".to_string())
     ("Distributed, Parallel, and Cluster Computing", arxiv_rss_link + &"cs.DC".to_string())
     ("Digital Libraries", arxiv_rss_link + &"cs.DL".to_string())
     ("Discrete Mathematics", arxiv_rss_link + &"cs.DM".to_string())
     ("Data Structures and Algorithms", arxiv_rss_link + &"cs.DS".to_string())
     ("Emerging Technologies", arxiv_rss_link + &"cs.ET".to_string())
     ("Formal Languages and Automata Theory", arxiv_rss_link + &"cs.FL".to_string())
     ("General Literature", arxiv_rss_link + &"cs.GL".to_string())
     ("Graphics", arxiv_rss_link + &"cs.GR".to_string())
     ("Computer Science and Game Theory", arxiv_rss_link + &"cs.GT".to_string())
     ("Human-Computer Interaction", arxiv_rss_link + &"cs.HC".to_string())
     ("Information Retrieval", arxiv_rss_link + &"cs.IR".to_string())
     ("Information Theory", arxiv_rss_link + &"cs.IT".to_string())
     ("Machine Learning", arxiv_rss_link + &"cs.LG".to_string())
     ("Logic in Computer Science", arxiv_rss_link + &"cs.LO".to_string())
     ("Multiagent Systems", arxiv_rss_link + &"cs.MA".to_string())
     ("Multimedia", arxiv_rss_link + &"cs.MM".to_string())
     ("Mathematical Software", arxiv_rss_link + &"cs.MS".to_string())
     ("Numerical Analysis", arxiv_rss_link + &"cs.NA".to_string())
     ("Neural and Evolutionary Computing", arxiv_rss_link + &"cs.NE".to_string())
     ("Networking and Internet Architecture", arxiv_rss_link + &"cs.NI".to_string())
     ("Other Computer Science", arxiv_rss_link + &"cs.OH".to_string())
     ("Operating Systems", arxiv_rss_link + &"cs.OS".to_string())
     ("Performance", arxiv_rss_link + &"cs.PF".to_string())
     ("Programming Languages", arxiv_rss_link + &"cs.PL".to_string())
     ("Robotics", arxiv_rss_link + &"cs.RO".to_string())
     ("Sound", arxiv_rss_link + &"cs.SC".to_string())
     ("Sound", arxiv_rss_link + &"cs.SD".to_string())
     ("Software Engineering", arxiv_rss_link + &"cs.SE".to_string())
     ("Social and Information Networks", arxiv_rss_link + &"cs.SI".to_string())
     ("Systems and Control", arxiv_rss_link + &"cs.SY".to_string())
     //Electrical Engineering and Systems Science
     ("Audio and Speech Processing", arxiv_rss_link + &"eess.AS".to_string())
     ("Image and Video Processing", arxiv_rss_link + &"eess.IV".to_string())
     ("Signal Processing", arxiv_rss_link + &"eess.SP".to_string())
     ("Systems and Control", arxiv_rss_link + &"eess.SY".to_string())
     //Mathematics
     ("Commutative Algebra", arxiv_rss_link + &"math.AC".to_string())
     ("Algebraic Geometry", arxiv_rss_link + &"math.AG".to_string())
     ("Analysis of PDEs", arxiv_rss_link + &"math.AP".to_string())
     ("Algebraic Topology", arxiv_rss_link + &"math.AT".to_string())
     ("Classical Analysis and ODEs", arxiv_rss_link + &"math.CA".to_string())
     ("Combinatorics", arxiv_rss_link + &"math.CO".to_string())
     ("Category Theory", arxiv_rss_link + &"math.CT".to_string())
     ("Complex Variables", arxiv_rss_link + &"math.CV".to_string())
     ("Differential Geometry", arxiv_rss_link + &"math.DG".to_string())
     ("Dynamical Systems", arxiv_rss_link + &"math.DS".to_string())
     ("Functional Analysis", arxiv_rss_link + &"math.FA".to_string())
     ("General Mathematics", arxiv_rss_link + &"math.GM".to_string())
     ("General Topology", arxiv_rss_link + &"math.GN".to_string())
     ("Group Theory", arxiv_rss_link + &"math.GR".to_string())
     ("Geometric Topology", arxiv_rss_link + &"math.GT".to_string())
     ("History and Overview", arxiv_rss_link + &"math.HO".to_string())
     ("Information Theory", arxiv_rss_link + &"math.IT".to_string())
     ("K-Theory and Homology", arxiv_rss_link + &"math.KT".to_string())
     ("Logic", arxiv_rss_link + &"math.LO".to_string())
     ("Metric Geometry", arxiv_rss_link + &"math.MG".to_string())
     ("Mathematical Physics", arxiv_rss_link + &"math.MP".to_string())
     ("Numerical Analysis", arxiv_rss_link + &"math.NA".to_string())
     ("Number Theory", arxiv_rss_link + &"math.NT".to_string())
     ("Operator Algebras", arxiv_rss_link + &"math.OA".to_string())
     ("Optimization and Control", arxiv_rss_link + &"math.OC".to_string())
     ("Probability", arxiv_rss_link + &"math.PR".to_string())
     ("Quantum Algebra", arxiv_rss_link + &"math.QA".to_string())
     ("Rings and Algebras", arxiv_rss_link + &"math.RA".to_string())
     ("Representation Theory", arxiv_rss_link + &"math.RT".to_string())
     ("Symplectic Geometry", arxiv_rss_link + &"math.SG".to_string())
     ("Spectral Theory", arxiv_rss_link + &"math.SP".to_string())
     ("Statistics Theory", arxiv_rss_link + &"math.ST".to_string())
     //Nonlinear Sciences
     ("Adaptation and Self-Organizing System", arxiv_rss_link + &"nlin.AO".to_string())
     ("Chaotic Dynamics", arxiv_rss_link + &"nlin.CD".to_string())
     ("Cellular Automata and Lattice Gases", arxiv_rss_link + &"nlin.CG".to_string())
     ("Pattern Formation and Solitons", arxiv_rss_link + &"nlin.PS".to_string())
     ("Exactly Solvable and Integrable Systems", arxiv_rss_link + &"nlin.SI".to_string())
     //physics
     ("Accelerator Physics", arxiv_rss_link + &"physics.acc-ph".to_string())
     ("Atmospheric and Oceanic Physics", arxiv_rss_link + &"physics.ao-ph".to_string())
     ("Applied Physics", arxiv_rss_link + &"physics.app-ph".to_string())
     ("Atomic and Molecular Clusters", arxiv_rss_link + &"physics.atm-clus".to_string())
     ("Atomic Physics", arxiv_rss_link + &"physics.atom-ph".to_string())
     ("Biological Physics", arxiv_rss_link + &"physics.bio-ph".to_string())
     ("Chemical Physics", arxiv_rss_link + &"physics.chem-ph".to_string())
     ("Classical Physics", arxiv_rss_link + &"physics.class-ph".to_string())
     ("Computational Physics", arxiv_rss_link + &"physics.comp-ph".to_string())
     ("Data Analysis, Statistics and Probability", arxiv_rss_link + &"physics.data-an".to_string())
     ("Physics Education", arxiv_rss_link + &"physics.ed-ph".to_string())
     ("Fluid Dynamics", arxiv_rss_link + &"physics.flu-dyn".to_string())
     ("General Physics", arxiv_rss_link + &"physics.gen-ph".to_string())
     ("Geophysics", arxiv_rss_link + &"physics.geo-ph".to_string())
     ("History and Philosophy of Physics", arxiv_rss_link + &"physics.hist-ph".to_string())
     ("Instrumentation and Detectors", arxiv_rss_link + &"physics.ins-det".to_string())
     ("Medical Physics", arxiv_rss_link + &"physics.med-ph".to_string())
     ("Optics", arxiv_rss_link + &"physics.optics".to_string())
     ("Plasma Physics", arxiv_rss_link + &"physics.plasm-ph".to_string())
     ("Popular Physics", arxiv_rss_link + &"physics.pop-ph".to_string())
     ("Physics and Society", arxiv_rss_link + &"physics.soc-ph".to_string())
     ("Space Physics", arxiv_rss_link + &"physics.space-ph".to_string())
     //Quantitative Biology
     ("Biomolecules", arxiv_rss_link + &"q-bio.BM".to_string())
     ("Cell Behavior", arxiv_rss_link + &"q-bio.CB".to_string())
     ("Genomics", arxiv_rss_link + &"q-bio.GN".to_string())
     ("Molecular Networks", arxiv_rss_link + &"q-bio.MN".to_string())
     ("Neurons and Cognition", arxiv_rss_link + &"q-bio.NC".to_string())
     ("Other Quantitative Biology", arxiv_rss_link + &"q-bio.OT".to_string())
     ("Populations and Evolution", arxiv_rss_link + &"q-bio.PE".to_string())
     ("Quantitative Methods", arxiv_rss_link + &"q-bio.QM".to_string())
     ("Subcellular Processes", arxiv_rss_link + &"q-bio.SC".to_string())
     ("Tissues and Organ", arxiv_rss_link + &"q-bio.TO".to_string())
     //Statistics
     ("General Relativity and Quantum Cosmology", arxiv_rss_link + &"gr-qc".to_string())
     ("High Energy Physics - Experiment", arxiv_rss_link + &"hep-ex".to_string())
     ("High Energy Physics - Lattice", arxiv_rss_link + &"hep-lat".to_string())
     ("High Energy Physics - Phenomenolog", arxiv_rss_link + &"hep-ph".to_string())
     ("High Energy Physics - Theory", arxiv_rss_link + &"hep-th".to_string())
     ("Quantum Physics", arxiv_rss_link + &"quant-ph".to_string())
     ("Nuclear Experiment", arxiv_rss_link + &"nucl-ex".to_string())
     ("Nuclear Theory", arxiv_rss_link + &"nucl-th".to_string())
     ("Mathematical Physic", arxiv_rss_link + &"math-ph".to_string())
     ]
     .iter().cloned().collect();
    arxiv_sections_links
}
