[workspace]
members = [
  "box_err_from_err",
  "enum_extention",
  "error_display",
  "gen_enum",
  "gen_enum_without_values",
  "git_info",
  "impl_display",
  "impl_from_for_upper_struct",
  "init_from_env",
  "provider_kind_from_config",
]
