use procedural_macros_lib::AllVariants;
use procedural_macros_lib::EnumVariantCount;

use strum_macros::EnumIter;

#[derive(
    AllVariants,
    EnumVariantCount,
    EnumIter,
    Clone,
    Debug,
    serde_derive::Serialize,
    serde_derive::Deserialize,
    PartialEq,
    Eq,
    Hash,
    Copy,
)]
pub enum EnvBoolVar {
    EnableProviders,
    EnableCleaningWarningLogsDirectory,
    EnableCleaningWarningLogsDbInMongo,
    EnableCleaningWarningLogsDbCollectionsInMongo,
    EnableTimeMeasurement,
    EnableProviderLinksLimit,
    EnableCommonProvidersLinksLimit,
    EnableRandomizeOrderForProvidersLinkPartsForMongo,

    EnablePartialSuccessPrints,
    EnableTimeMeasurementPrints,
    EnableCleaningWarningLogsDirectoryPrints,
    EnableInfoPrints,
    EnableAllProvidersPrints,
    EnableErrorPrintsForAllProviders,
    EnableWarningHighPrintsForAllProviders,
    EnableWarningLowPrintsForAllProviders,
    EnableSuccessPrintsForAllProviders,
    EnablePartialSuccessPrintsForAllProviders,
    EnableTimeMeasurementPrintsForAllProviders,
    EnableCleaningWarningLogsDirectoryPrintsForAllProviders,
    EnableInfoPrintsForAllProviders,
    EnableWriteErrorLogsInLocalFolder,
    EnableWriteErrorLogsInMongo,

    EnableInitializeMongoWithProvidersLinkParts,
    EnableInitializeMongoWithArxivLinkParts,
    EnableInitializeMongoWithBiorxivLinkParts,
    EnableInitializeMongoWithGithubLinkParts,
    EnableInitializeMongoWithHabrLinkParts,
    EnableInitializeMongoWithMedrxivLinkParts,
    EnableInitializeMongoWithRedditLinkParts,
    EnableInitializeMongoWithTwitterLinkParts,

    EnableArxiv,
    EnableBiorxiv,
    EnableGithub,
    EnableHabr,
    EnableMedrxiv,
    EnableReddit,
    EnableTwitter,

    EnablePrints,
    EnablePrintsArxiv,
    EnablePrintsBiorxiv,
    EnablePrintsGithub,
    EnablePrintsHabr,
    EnablePrintsMedrxiv,
    EnablePrintsReddit,
    EnablePrintsTwitter,

    EnableWarningHighPrints,
    EnableWarningHighPrintsForArxiv,
    EnableWarningHighPrintsForBiorxiv,
    EnableWarningHighPrintsForGithub,
    EnableWarningHighPrintsForHabr,
    EnableWarningHighPrintsForMedrxiv,
    EnableWarningHighPrintsForReddit,
    EnableWarningHighPrintsForTwitter,

    EnableWarningLowPrints,
    EnableWarningLowPrintsForArxiv,
    EnableWarningLowPrintsForBiorxiv,
    EnableWarningLowPrintsForGithub,
    EnableWarningLowPrintsForHabr,
    EnableWarningLowPrintsForMedrxiv,
    EnableWarningLowPrintsForReddit,
    EnableWarningLowPrintsForTwitter,

    EnableErrorPrints,
    EnableErrorPrintsForArxiv,
    EnableErrorPrintsForBiorxiv,
    EnableErrorPrintsForGithub,
    EnableErrorPrintsForHabr,
    EnableErrorPrintsForMedrxiv,
    EnableErrorPrintsForReddit,
    EnableErrorPrintsForTwitter,

    EnableSuccessPrints,
    EnableSuccessPrintsForArxiv,
    EnableSuccessPrintsForBiorxiv,
    EnableSuccessPrintsForGithub,
    EnableSuccessPrintsForHabr,
    EnableSuccessPrintsForMedrxiv,
    EnableSuccessPrintsForReddit,
    EnableSuccessPrintsForTwitter,

    EnablePartialSuccessPrintsForArxiv,
    EnablePartialSuccessPrintsForBiorxiv,
    EnablePartialSuccessPrintsForGithub,
    EnablePartialSuccessPrintsForHabr,
    EnablePartialSuccessPrintsForMedrxiv,
    EnablePartialSuccessPrintsForReddit,
    EnablePartialSuccessPrintsForTwitter,

    EnableCleaningWarningLogsDirectoryForArxiv,
    EnableCleaningWarningLogsDirectoryForBiorxiv,
    EnableCleaningWarningLogsDirectoryForGithub,
    EnableCleaningWarningLogsDirectoryForHabr,
    EnableCleaningWarningLogsDirectoryForMedrxiv,
    EnableCleaningWarningLogsDirectoryForReddit,
    EnableCleaningWarningLogsDirectoryForTwitter,

    EnableCleaningWarningLogsDbInMongoForArxiv,
    EnableCleaningWarningLogsDbInMongoForBiorxiv,
    EnableCleaningWarningLogsDbInMongoForGithub,
    EnableCleaningWarningLogsDbInMongoForHabr,
    EnableCleaningWarningLogsDbInMongoForMedrxiv,
    EnableCleaningWarningLogsDbInMongoForReddit,
    EnableCleaningWarningLogsDbInMongoForTwitter,

    EnableCleaningWarningLogsDbCollectionsInMongoForArxiv,
    EnableCleaningWarningLogsDbCollectionsInMongoForBiorxiv,
    EnableCleaningWarningLogsDbCollectionsInMongoForGithub,
    EnableCleaningWarningLogsDbCollectionsInMongoForHabr,
    EnableCleaningWarningLogsDbCollectionsInMongoForMedrxiv,
    EnableCleaningWarningLogsDbCollectionsInMongoForReddit,
    EnableCleaningWarningLogsDbCollectionsInMongoForTwitter,

    EnableTimeMeasurementForArxiv,
    EnableTimeMeasurementForBiorxiv,
    EnableTimeMeasurementForGithub,
    EnableTimeMeasurementForHabr,
    EnableTimeMeasurementForMedrxiv,
    EnableTimeMeasurementForReddit,
    EnableTimeMeasurementForTwitter,

    EnableInfoForArxiv,
    EnableInfoForBiorxiv,
    EnableInfoForGithub,
    EnableInfoForHabr,
    EnableInfoForMedrxiv,
    EnableInfoForReddit,
    EnableInfoForTwitter,

    EnableLinksLimitForArxiv,
    EnableLinksLimitForBiorxiv,
    EnableLinksLimitForGithub,
    EnableLinksLimitForHabr,
    EnableLinksLimitForMedrxiv,
    EnableLinksLimitForReddit,
    EnableLinksLimitForTwitter,

    EnableRandomizeOrderForArxivLinkPartsForMongo,
    EnableRandomizeOrderForBiorxivLinkPartsForMongo,
    EnableRandomizeOrderForGithubLinkPartsForMongo,
    EnableRandomizeOrderForHabrLinkPartsForMongo,
    EnableRandomizeOrderForMedrxivLinkPartsForMongo,
    EnableRandomizeOrderForRedditLinkPartsForMongo,
    EnableRandomizeOrderForTwitterLinkPartsForMongo,
}

impl EnvBoolVar {
    pub fn get_length() -> usize {
        ENUM_LENGTH
    }
}
