[github_authorization]
github_name = "example"
github_token = "example"

[reddit_authorization]
reddit_user_agent = "example"
reddit_client_id = "example"
reddit_client_secret = "example"
reddit_username = "example"
reddit_password = "example"

[mongo_own_authorization]
mongo_own_login = "example"
mongo_own_password = "example"
mongo_own_ip = "example"
mongo_own_port = "example"

[mongo_cloud_authorization]
mongo_cloud_login = "example"
mongo_cloud_password = "example"
mongo_cloud_cluster_name = "example"
mongo_cloud_cluster_params = "example"