
use serde::de;
use serde::ser;
use std::error::Error;
use std::fmt;

impl fmt::Display for ConfigError {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        match *self {
            ConfigError::Frozen  => write!(f, "{}", self.to_string()),
            ConfigError::Message(ref s) => write!(f, "{}", s),
            _ => write!(f, "dfhdfhdfh{}", self.to_string()),
        }
    }
}

impl Error for ConfigError {
    // is it deprecated?
    // fn description(&self) -> &str {
    //     match *self {
    //         ConfigError::Frozen => "configuration is frozen",
    //         _ => "configuration error",
    //     }
    // }
    //dont know about it yet
    // fn cause(&self) -> Option<&Error> {
    //     match *self {
    //         ConfigError::Foreign(ref cause) | ConfigError::FileParse { ref cause, .. } => {
    //             Some(cause.as_ref())
    //         }
    //         ConfigError::Frozen => "configuration is frozen",
    //         _ => None,
    //     }
    // }
}

impl de::Error for ConfigError {
    fn custom<T: fmt::Display>(msg: T) -> Self {
        ConfigError::Message(msg.to_string())
    }
}

impl ser::Error for ConfigError {
    fn custom<T: fmt::Display>(msg: T) -> Self {
        ConfigError::Message(msg.to_string())
    }
}

#[derive(Debug)] 
pub enum ConfigError {
    Frozen,
    Message(String),
    ConfigGithubAuthorizationGithubNameError,
    ConfigGithubAuthorizationGithubTokenError,
    ConfigRedditAuthorizationRedditUserAgentError,
    ConfigRedditAuthorizationRedditClientIdError,
    RedditAuthorizationRedditClientSecretError,
    RedditAuthorizationRedditUsernameError,
    RedditAuthorizationRedditPasswordError,
    ParamsStartingCheckLinkError,
    ConfigParamsUserCredentialsDummyHandleError,
    ParamsWarningLogsDirectoryNameError,
    ParamsUnhandledSuccessHandledSuccessAreThereItemsInitializedPostsDirError,
    ParamsEnableProvidersError,
    ParamsEnableCleaningWarningLogsDirectoryError,
    ConfigParamsEnableCleaningWarningLogsDbInMongoError,
    ConfigParamsEnableCleaningWarningLogsDbCollectionsInMongoError,
    ConfigParamsEnableTimeMeasurementError,
    ConfigParamsEnableProviderLinksLimitError,
    ConfigParamsEnableCommonProvidersLinksLimitError,
    ConfigParamsCommonProvidersLinksLimitError,
    ConfigParamsEnableRandomizeOrderForProvidersLinkPartsForMongoError,
    ConfigParamsEnablePrintsError,
    ConfigParamsEnableErrorPrintsError,
    ConfigParamsEnableWarningHighPrintsError,
    ConfigParamsEnableWarningLowPrintsError,
    ConfigParamsEnableSuccessPrintsError,
    ConfigParamsEnablePartialSuccessPrintsError,
    ConfigParamsEnableTimeMeasurementPrintsError,
    ConfigParamsEnableCleaningWarningLogsDirectoryPrintsError,
    ConfigParamsEnableInfoPrintsError,
    ConfigParamsEnableAllProvidersPrintsError,
    ConfigParamsEnableErrorPrintsForAllProvidersError,
    ConfigParamsEnableWarningHighPrintsForAllProvidersError,
    ConfigParamsEnableWarningLowPrintsForAllProvidersError,
    ConfigParamsEnableSuccessPrintsForAllProvidersError,
    ConfigParamsEnablePartialSuccessPrintsForAllProvidersError,
    ConfigParamsEnableTimeMeasurementPrintsForAllProvidersError,
    ConfigParamsEnableCleaningWarningLogsDirectoryPrintsForAllProvidersError,
    ConfigParamsEnableInfoPrintsForAllProvidersError,
    ConfigParamsEnableWriteErrorLogsInLocalFolderError,
    ConfigParamsEnableWriteErrorLogsInMongoError,
    ConfigParamsEnableInitializeMongoWithProvidersLinkPartsError,
    ConfigMongoParamsProvidersDbNameHandleError,
    ConfigMongoParamsProvidersDbCollectionHandleSecondPartError,
    ConfigMongoParamsProvidersDbCollectionDocumentFieldNameHandleError,
    ConfigMongoParamsDbProvidersLogsNameHandleError,
    ConfigMongoParamsDbProvidersLogsCollectionHandleSecondPartError,
    ConfigMongoParamsDbProvidersLogsCollectionDocumentFieldNameHandleError,
    ConfigMongoParamsPathToProviderLinkPartsFolderError,
    ConfigMongoParamsLogFileExtensionError,
    ConfigMongoParamsEnableInitializeMongoWithProvidersLinkPartsEnableInitializeMongoWithArxivLinkPartsError,
    ConfigMongoParamsEnableInitializeMongoWithProvidersLinkPartsEnableInitializeMongoWithBiorxivLinkPartsError,
    ConfigMongoParamsEnableInitializeMongoWithProvidersLinkPartsEnableInitializeMongoWithGithubLinkPartsError,
    ConfigMongoParamsEnableInitializeMongoWithProvidersLinkPartsEnableInitializeMongoWithHabrLinkPartsError,
    ConfigMongoParamsEnableInitializeMongoWithProvidersLinkPartsEnableInitializeMongoWithMedrxivLinkPartsError,
    ConfigMongoParamsEnableInitializeMongoWithProvidersLinkPartsEnableInitializeMongoWithRedditLinkPartsError,
    ConfigMongoParamsEnableInitializeMongoWithProvidersLinkPartsEnableInitializeMongoWithTwitterLinkPartsError,
    ConfigMongoParamsMongoUrlPartsMongoFirstHandleUrlPartError,
    ConfigMongoParamsMongoUrlPartsMongoSecondHandleUrlPartError,
    ConfigMongoParamsMongoUrlPartsMongoThirdHandleUrlPartError,
    ConfigMongoParamsMongoUrlPartsMongoFourthHandleUrlPartError,
    ConfigMongoParamsMongoUrlPartsMongoFifthHandleUrlPartError,
    ConfigMongoAuthorizationMongoLoginError,
    ConfigMongoAuthorizationMongoPasswordError,
    ConfigMongoAuthorizationMongoIpError,
    ConfigMongoAuthorizationMongoPortError,
    ConfigMongoAuthorizationMongoParamsError,
    ConfigPostgresParamsPostgresUrlPartsPostgresFirstHandleUrlPartError,
    ConfigPostgresParamsPostgresUrlPartsPostgresSecondHandleUrlPartError,
    ConfigPostgresParamsPostgresUrlPartsPostgresThirdHandleUrlPartError,
    ConfigPostgresParamsPostgresUrlPartsPostgresFourthHandleUrlPartError,
    ConfigPostgresParamsPostgresUrlPartsPostgresFifthHandleUrlPartError,
    ConfigPostgresAuthorizationPostgresLoginError,
    ConfigPostgresAuthorizationPostgresPasswordError,
    ConfigPostgresAuthorizationPostgresIpError,
    ConfigPostgresAuthorizationPostgresPortError,
    ConfigPostgresAuthorizationPostgresDbError,
    ConfigEnableProvidersEnableArxivError,
    ConfigEnableProvidersEnableBiorxivError,
    ConfigEnableProvidersEnableGithubError,
    ConfigEnableProvidersEnableHabrError,
    ConfigEnableProvidersEnableMedrxivError,
    ConfigEnableProvidersEnableRedditError,
    ConfigEnableProvidersEnableTwitterError,
    ConfigProvidersCheckLinksArxivLinkError,
    ConfigProvidersCheckLinksBiorxivLinkError,
    ConfigProvidersCheckLinksGithubLinkError,
    ConfigProvidersCheckLinksHabrLinkError,
    ConfigProvidersCheckLinksMedrxivLinkError,
    ConfigProvidersCheckLinksRedditLinkError,
    ConfigProvidersCheckLinksTwitterLinkError,
    ConfigEnableProvidersPrintsEnablePrintsArxivError,
    ConfigEnableProvidersPrintsEnablePrintsBiorxivError,
    ConfigEnableProvidersPrintsEnablePrintsGithubError,
    ConfigEnableProvidersPrintsEnablePrintsHabrError,
    ConfigEnableProvidersPrintsEnablePrintsMedrxivError,
    ConfigEnableProvidersPrintsEnablePrintsRedditError,
    ConfigEnableProvidersPrintsEnablePrintsTwitterError,
    ConfigEnableWarningHighProvidersPrintsEnableWarningHighPrintsForArxivError,
    ConfigEnableWarningHighProvidersPrintsEnableWarningHighPrintsForBiorxivError,
    ConfigEnableWarningHighProvidersPrintsEnableWarningHighPrintsForGithubError,
    ConfigEnableWarningHighProvidersPrintsEnableWarningHighPrintsForHabrError,
    ConfigEnableWarningHighProvidersPrintsEnableWarningHighPrintsForMedrxivError,
    ConfigEnableWarningHighProvidersPrintsEnableWarningHighPrintsForRedditError,
    ConfigEnableWarningHighProvidersPrintsEnableWarningHighPrintsForTwitterError,
    ConfigEnableWarningLowProvidersPrintsEnableWarningLowPrintsForArxivError,
    ConfigEnableWarningLowProvidersPrintsEnableWarningLowPrintsForBiorxivError,
    ConfigEnableWarningLowProvidersPrintsEnableWarningLowPrintsForGithubError,
    ConfigEnableWarningLowProvidersPrintsEnableWarningLowPrintsForHabrError,
    ConfigEnableWarningLowProvidersPrintsEnableWarningLowPrintsForMedrxivError,
    ConfigEnableWarningLowProvidersPrintsEnableWarningLowPrintsForRedditError,
    ConfigEnableWarningLowProvidersPrintsEnableWarningLowPrintsForTwitterError,
    ConfigEnableSuccessProvidersPrintsEnableSuccessPrintsForArxivError,
    ConfigEnableSuccessProvidersPrintsEnableSuccessPrintsForBiorxivError,
    ConfigEnableSuccessProvidersPrintsEnableSuccessPrintsForGithubError,
    ConfigEnableSuccessProvidersPrintsEnableSuccessPrintsForHabrError,
    ConfigEnableSuccessProvidersPrintsEnableSuccessPrintsForMedrxivError,
    ConfigEnableSuccessProvidersPrintsEnableSuccessPrintsForRedditError,
    ConfigEnableSuccessProvidersPrintsEnableSuccessPrintsForTwitterError,
    ConfigEnablePartialSuccessProvidersPrintsEnablePartialSuccessPrintsForArxivError,
    ConfigEnablePartialSuccessProvidersPrintsEnablePartialSuccessPrintsForBiorxivError,
    ConfigEnablePartialSuccessProvidersPrintsEnablePartialSuccessPrintsForGithubError,
    ConfigEnablePartialSuccessProvidersPrintsEnablePartialSuccessPrintsForHabrError,
    ConfigEnablePartialSuccessProvidersPrintsEnablePartialSuccessPrintsForMedrxivError,
    ConfigEnablePartialSuccessProvidersPrintsEnablePartialSuccessPrintsForRedditError,
    ConfigEnablePartialSuccessProvidersPrintsEnablePartialSuccessPrintsForTwitterError,
    ConfigEnableErrorProvidersPrintsEnableErrorPrintsForArxivError,
    ConfigEnableErrorProvidersPrintsEnableErrorPrintsForBiorxivError,
    ConfigEnableErrorProvidersPrintsEnableErrorPrintsForGithubError,
    ConfigEnableErrorProvidersPrintsEnableErrorPrintsForHabrError,
    ConfigEnableErrorProvidersPrintsEnableErrorPrintsForMedrxivError,
    ConfigEnableErrorProvidersPrintsEnableErrorPrintsForRedditError,
    ConfigEnableErrorProvidersPrintsEnableErrorPrintsForTwitterError,
    ConfigEnableProvidersCleaningWarningLogsDirectoryEnableCleaningWarningLogsDirectoryForArxivError,
    ConfigEnableProvidersCleaningWarningLogsDirectoryEnableCleaningWarningLogsDirectoryForBiorxivError,
    ConfigEnableProvidersCleaningWarningLogsDirectoryEnableCleaningWarningLogsDirectoryForGithubError,
    ConfigEnableProvidersCleaningWarningLogsDirectoryEnableCleaningWarningLogsDirectoryForHabrError,
    ConfigEnableProvidersCleaningWarningLogsDirectoryEnableCleaningWarningLogsDirectoryForMedrxivError,
    ConfigEnableProvidersCleaningWarningLogsDirectoryEnableCleaningWarningLogsDirectoryForRedditError,
    ConfigEnableProvidersCleaningWarningLogsDirectoryEnableCleaningWarningLogsDirectoryForTwitterError,
    ConfigEnableProvidersCleaningWarningLogsDbInMongoEnableCleaningWarningLogsDbInMongoForArxivError,
    ConfigEnableProvidersCleaningWarningLogsDbInMongoEnableCleaningWarningLogsDbInMongoForBiorxivError,
    ConfigEnableProvidersCleaningWarningLogsDbInMongoEnableCleaningWarningLogsDbInMongoForGithubError,
    ConfigEnableProvidersCleaningWarningLogsDbInMongoEnableCleaningWarningLogsDbInMongoForHabrError,
    ConfigEnableProvidersCleaningWarningLogsDbInMongoEnableCleaningWarningLogsDbInMongoForMedrxivError,
    ConfigEnableProvidersCleaningWarningLogsDbInMongoEnableCleaningWarningLogsDbInMongoForRedditError,
    ConfigEnableProvidersCleaningWarningLogsDbInMongoEnableCleaningWarningLogsDbInMongoForTwitterError,
    ConfigEnableProvidersCleaningWarningLogsDbCollectionsInMongoEnableCleaningWarningLogsDbCollectionsInMongoForArxivError,
    ConfigEnableProvidersCleaningWarningLogsDbCollectionsInMongoEnableCleaningWarningLogsDbCollectionsInMongoForBiorxivError,
    ConfigEnableProvidersCleaningWarningLogsDbCollectionsInMongoEnableCleaningWarningLogsDbCollectionsInMongoForGithubError,
    ConfigEnableProvidersCleaningWarningLogsDbCollectionsInMongoEnableCleaningWarningLogsDbCollectionsInMongoForHabrError,
    ConfigEnableProvidersCleaningWarningLogsDbCollectionsInMongoEnableCleaningWarningLogsDbCollectionsInMongoForMedrxivError,
    ConfigEnableProvidersCleaningWarningLogsDbCollectionsInMongoEnableCleaningWarningLogsDbCollectionsInMongoForRedditError,
    ConfigEnableProvidersCleaningWarningLogsDbCollectionsInMongoEnableCleaningWarningLogsDbCollectionsInMongoForTwitterError,
    ConfigEnableProvidersTimeMeasurementEnableTimeMeasurementForArxivError,
    ConfigEnableProvidersTimeMeasurementEnableTimeMeasurementForBiorxivError,
    ConfigEnableProvidersTimeMeasurementEnableTimeMeasurementForGithubError,
    ConfigEnableProvidersTimeMeasurementEnableTimeMeasurementForHabrError,
    ConfigEnableProvidersTimeMeasurementEnableTimeMeasurementForMedrxivError,
    ConfigEnableProvidersTimeMeasurementEnableTimeMeasurementForRedditError,
    ConfigEnableProvidersTimeMeasurementEnableTimeMeasurementForTwitterError,
    ConfigEnableProvidersInfoEnableInfoForArxivError,
    ConfigEnableProvidersInfoEnableInfoForBiorxivError,
    ConfigEnableProvidersInfoEnableInfoForGithubError,
    ConfigEnableProvidersInfoEnableInfoForHabrError,
    ConfigEnableProvidersInfoEnableInfoForMedrxivError,
    ConfigEnableProvidersInfoEnableInfoForRedditError,
    ConfigEnableProvidersInfoEnableInfoForTwitterError,
    ConfigEnableProvidersLinksLimitsEnableLinksLimitForArxivError,
    ConfigEnableProvidersLinksLimitsEnableLinksLimitForBiorxivError,
    ConfigEnableProvidersLinksLimitsEnableLinksLimitForGithubError,
    ConfigEnableProvidersLinksLimitsEnableLinksLimitForHabrError,
    ConfigEnableProvidersLinksLimitsEnableLinksLimitForMedrxivError,
    ConfigEnableProvidersLinksLimitsEnableLinksLimitForRedditError,
    ConfigEnableProvidersLinksLimitsEnableLinksLimitForTwitterError,
    ConfigProvidersLinksLimitsLinksLimitForArxivError,
    ConfigProvidersLinksLimitsLinksLimitForBiorxivError,
    ConfigProvidersLinksLimitsLinksLimitForGithubError,
    ConfigProvidersLinksLimitsLinksLimitForHabrError,
    ConfigProvidersLinksLimitsLinksLimitForMedrxivError,
    ConfigProvidersLinksLimitsLinksLimitForRedditError,
    ConfigProvidersLinksLimitsLinksLimitForTwitterError,
    ConfigEnableRandomizeOrderForProvidersLinkPartsForMongoEnableRandomizeOrderForArxivLinkPartsForMongoError,
    ConfigEnableRandomizeOrderForProvidersLinkPartsForMongoEnableRandomizeOrderForBiorxivLinkPartsForMongoError,
    ConfigEnableRandomizeOrderForProvidersLinkPartsForMongoEnableRandomizeOrderForGithubLinkPartsForMongoError,
    ConfigEnableRandomizeOrderForProvidersLinkPartsForMongoEnableRandomizeOrderForHabrLinkPartsForMongoError,
    ConfigEnableRandomizeOrderForProvidersLinkPartsForMongoEnableRandomizeOrderForMedrxivLinkPartsForMongoError,
    ConfigEnableRandomizeOrderForProvidersLinkPartsForMongoEnableRandomizeOrderForRedditLinkPartsForMongoError,
    ConfigEnableRandomizeOrderForProvidersLinkPartsForMongoEnableRandomizeOrderForTwitterLinkPartsForMongoError,
    ConfigPrintColorsErrorRedError,
    ConfigPrintColorsErrorGreenError,
    ConfigPrintColorsErrorBlueError,
    ConfigPrintColorsWarningHighRedError,
    ConfigPrintColorsWarningHighGreenError,
    ConfigPrintColorsWarningHighBlueError,
    ConfigPrintColorsWarningLowRedError,
    ConfigPrintColorsWarningLowGreenError,
    ConfigPrintColorsWarningLowBlueError,
    ConfigPrintColorsSuccessRedError,
    ConfigPrintColorsSuccessGreenError,
    ConfigPrintColorsSuccessBlueError,
    ConfigPrintColorsPartialSuccessRedError,
    ConfigPrintColorsPartialSuccessGreenError,
    ConfigPrintColorsPartialSuccessBlueError,
    ConfigPrintColorsCleaningRedError,
    ConfigPrintColorsCleaningGreenError,
    ConfigPrintColorsCleaningBlueError,
    ConfigPrintColorsTimeMeasurementRedError,
    ConfigPrintColorsTimeMeasurementGreenError,
    ConfigPrintColorsTimeMeasurementBlueError,
    ConfigPrintColorsInfoRedError,
    ConfigPrintColorsInfoGreenError,
    ConfigPrintColorsInfoBlueError,
}
    