use tufa_common::traits::error_logs_logic::error_log::ErrorLog;

pub fn dev() {
    let _f = one();
    if let Err(e) = _f {
        //todo - this actually must be a config struct function, not an error - config.error_log(e)
        println!("{}", *e);
        e.error_log(once_cell::sync::Lazy::force(
            &crate::global_variables::runtime::config::CONFIG,
        ));
    }
}

pub fn dev_with_deserialize() {
    let _f = one_with_deserialize();
    if let Err(e) = _f {
        println!("------++++-___");
        println!("{}", e);
    }
}
//from implementation was not generated by thiserror with 'a lifetime https://github.com/dtolnay/thiserror/issues/68

#[derive(
    Debug, thiserror::Error, serde::Serialize, error_occurence::ImplErrorOccurenceFromTufaCommon,
)]
pub enum OneWrapperError<'a> {
    Something {
        inner_error: crate::dev::OneWrapperErrorEnum<'a>,
        code_occurence: tufa_common::common::code_occurence::CodeOccurence<'a>,
    },
}

// impl<'a> std::fmt::Display for OneWrapperError<'a> {
//     fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
//         use tufa_common::traits::error_logs_logic::to_string_without_config::ToStringWithoutConfig;
//         write!(f, "{}", self.to_string_without_config())
//     }
// }

// impl<'a, ConfigGeneric>
//     tufa_common::traits::error_logs_logic::source_to_string_with_config::SourceToStringWithConfig<
//         'a,
//         ConfigGeneric,
//     > for OneWrapperError<'a>
// where
//     ConfigGeneric: tufa_common::traits::fields::GetSourcePlaceType
//         + tufa_common::traits::fields::GetTimezone
//         + tufa_common::traits::get_server_address::GetServerAddress,
// {
//     fn source_to_string_with_config(&self, config: &ConfigGeneric) -> String {
//         match self {
//             OneWrapperError::Something {
//                 inner_error,
//                 code_occurence: _code_occurence,
//             } => {
//                 use tufa_common::traits::error_logs_logic::to_string_with_config::ToStringWithConfigForSourceToStringWithConfig;
//                 inner_error.to_string_with_config_for_source_to_string_with_config(config)
//             }
//         }
//     }
// }

// impl<'a> tufa_common::traits::error_logs_logic::source_to_string_without_config::SourceToStringWithoutConfig<'a> for OneWrapperError<'a> {
//     fn source_to_string_without_config(&self) -> String {
//         match self {
//             OneWrapperError::Something { inner_error, code_occurence: _code_occurence } => {
//                 use tufa_common::traits::error_logs_logic::to_string_without_config::ToStringWithoutConfig;
//                 inner_error.to_string_without_config()
//             },
//         }
//     }
// }

// impl<'a> tufa_common::traits::error_logs_logic::get_code_occurence::GetCodeOccurence<'a>
//     for OneWrapperError<'a>
// {
//     fn get_code_occurence(&self) -> &tufa_common::common::code_occurence::CodeOccurence {
//         match self {
//             OneWrapperError::Something {
//                 inner_error: _inner_error,
//                 code_occurence,
//             } => code_occurence,
//         }
//     }
// }

// #[derive(Debug, thiserror::Error, serde::Serialize, serde::Deserialize)]
// pub enum OneWrapperErrorWithDeserialize<'a> {
//     Something {
//         #[serde(borrow)]
//         inner_error: OneWrapperErrorEnumWithDeserialize<'a>,
//         #[serde(borrow)]
//         code_occurence: tufa_common::common::code_occurence::CodeOccurenceWithDeserialize<'a>,
//     },
// }

// impl<'a> std::fmt::Display for OneWrapperErrorWithDeserialize<'a> {
//     fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
//         use tufa_common::traits::error_logs_logic::to_string_without_config::ToStringWithoutConfigWithDeserialize;
//         write!(f, "{}", self.to_string_without_config_with_deserialize())
//     }
// }

// impl<'a> tufa_common::traits::error_logs_logic::source_to_string_without_config::SourceToStringWithoutConfig<'a> for OneWrapperErrorWithDeserialize<'a> {
//     fn source_to_string_without_config(&self) -> String {
//         match self {
//             OneWrapperErrorWithDeserialize::Something { inner_error, code_occurence: _code_occurence } => {
//                 use tufa_common::traits::error_logs_logic::to_string_without_config::ToStringWithoutConfigWithDeserialize;
//                 inner_error.to_string_without_config_with_deserialize()
//             },
//         }
//     }
// }

// impl<'a>
//     tufa_common::traits::error_logs_logic::get_code_occurence::GetCodeOccurenceWithDeserialize<'a>
//     for OneWrapperErrorWithDeserialize<'a>
// {
//     fn get_code_occurence_with_deserialize(
//         &self,
//     ) -> &tufa_common::common::code_occurence::CodeOccurenceWithDeserialize<'a> {
//         match self {
//             OneWrapperErrorWithDeserialize::Something {
//                 inner_error: _inner_error,
//                 code_occurence,
//             } => code_occurence,
//         }
//     }
// }

#[derive(
    Debug, thiserror::Error, serde::Serialize, error_occurence::ImplErrorOccurenceFromTufaCommon,
)]
pub enum OneWrapperErrorEnum<'a> {
    Three(tufa_common::dev::ThreeWrapperError<'a>),
}

// impl<'a> std::fmt::Display for OneWrapperErrorEnum<'a> {
//     fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
//         use tufa_common::traits::error_logs_logic::to_string_without_config::ToStringWithoutConfig;
//         write!(f, "{}", self.to_string_without_config())
//     }
// }

// impl<'a, ConfigGeneric>
//     tufa_common::traits::error_logs_logic::to_string_with_config::ToStringWithConfigForSourceToStringWithConfig<
//         'a,
//         ConfigGeneric,
//     > for OneWrapperErrorEnum<'a>
// where
//     ConfigGeneric: tufa_common::traits::fields::GetSourcePlaceType
//         + tufa_common::traits::fields::GetTimezone
//         + tufa_common::traits::get_server_address::GetServerAddress,
// {
//     fn to_string_with_config_for_source_to_string_with_config(&self, config: &ConfigGeneric) -> String {
//         match self {
//             OneWrapperErrorEnum::Three(i) => {
//                 i.to_string_with_config_for_source_to_string_with_config(config)
//             }
//         }
//     }
// }

// impl<'a> tufa_common::traits::error_logs_logic::to_string_without_config::ToStringWithoutConfig<'a>
//     for OneWrapperErrorEnum<'a>
// {
//     fn to_string_without_config(&self) -> String {
//         match self {
//             OneWrapperErrorEnum::Three(i) => i.to_string_without_config(),
//         }
//     }
// }

// #[derive(Debug, thiserror::Error, serde::Serialize, serde::Deserialize)]
// pub enum OneWrapperErrorEnumWithDeserialize<'a> {
//     #[serde(borrow)]
//     Three(tufa_common::dev::ThreeWrapperErrorWithDeserialize<'a>),
// }

// impl<'a> std::fmt::Display for OneWrapperErrorEnumWithDeserialize<'a> {
//     fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
//         use tufa_common::traits::error_logs_logic::to_string_without_config::ToStringWithoutConfigWithDeserialize;
//         write!(f, "{}", self.to_string_without_config_with_deserialize())
//     }
// }

// impl<'a>
//     tufa_common::traits::error_logs_logic::to_string_without_config::ToStringWithoutConfigWithDeserialize<
//         'a,
//     > for OneWrapperErrorEnumWithDeserialize<'a>
// {
//     fn to_string_without_config_with_deserialize(&self) -> String {
//         match self {
//             OneWrapperErrorEnumWithDeserialize::Three(i) => {
//                 i.to_string_without_config_with_deserialize()
//             }
//         }
//     }
// }

pub fn one<'a>() -> Result<(), Box<OneWrapperError<'a>>> {
    if let Err(e) = tufa_common::dev::three() {
        return Err(Box::new(OneWrapperError::Something {
            inner_error: crate::dev::OneWrapperErrorEnum::Three(*e),
            code_occurence: tufa_common::code_occurence!(),
        }));
    }
    Ok(())
}

pub fn one_with_deserialize<'a>() -> Result<(), Box<OneWrapperErrorWithDeserialize<'a>>> {
    if let Err(e) = tufa_common::dev::three_with_deserialize() {
        return Err(Box::new(OneWrapperErrorWithDeserialize::Something {
            inner_error: crate::dev::OneWrapperErrorEnumWithDeserialize::Three(*e),
            code_occurence: tufa_common::common::code_occurence::CodeOccurenceWithDeserialize::new(
                &tufa_common::global_variables::compile_time::git_info::GIT_INFO,
                file!(),
                line!(),
                column!(),
            ),
        }));
    }
    Ok(())
}
