# -------------------
# Github actions
# -------------------
name: CI
env: 
   APPLICATION_NAME: "tufa"
   PACKAGE_NAME: "tufa-backend-package-${{ github.sha }}"
   

on: 
  push:
    branches: 
      - master
      
jobs: 
  my-testing1:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print_Hello_Message1
        run: echo "hello_world1"
        
      - name: Execute_few_commands
        run: |
          echo "hello_message_few_commands1"
          echo "hello_message_few_commands2"
          echo "hello_message_few_commands3 Application_name: ${{ env.APPLICATION_NAME}}"
          echo "hello_message_few_commands3 Package_name: ${{ env.PACKAGE_NAME}}"
        
  my-testing2:
    runs-on: ubuntu-latest
    needs: [my-testing1]
    
    steps:
      - name: Print_Hello_Message2
        run: echo "hello_world2"
        
      - name: List_current_folder
        run: ls -la
  
