name: CI
env: 
   APPLICATION_NAME: "tufa"
   PACKAGE_NAME: "tufa-backend-package-${{ github.sha }}"

on: 
  push:
    branches: 
      - master
      
jobs:   
  tests:
    runs-on: ubuntu-latest
#     needs: [my-testing1]
    
    steps:
      - name: Git clone my repo
        uses: actions/checkout@v1 
        
      - name: lets test cargo if it is here
        run: cargo --version
        
      - name: lets test rustc if it is here
        run: rustc --version
        
      - name: Rustup default nightly
        run: rustup default nightly
        
      - name: Rustup update
        run: rustup update
        
      - name: check_config_files_exists
        run: cargo +nightly test check_config_files_exists
        
      - name: check_compromised_reddit_auth_info
        run: cargo +nightly test check_compromised_reddit_auth_info
  
